src/ghdldrv/ghdldrv.adb

See https://mail.gna.org/public/ghdl-discuss/2015-08/msg00050.html for original discussion, quoted below.
>If building a project with GHDL that will be embedded within another
>program via ghdl_main, it seems that there is no equivalent of `ghdl -m`
>that automatically analyzes dependencies.
>
>Right now I'm using:
>
>    ghdl -m $(GHDLFLAGS) toplevel_tb || true
>    ghdl --bind $(GHDLFLAGS) toplevel_tb # not absolutely necessary,
>but catches errors that would have otherwise been ignored by above
>line
>
>That runs -m as far as it will get (which isn't all the way, since my
>VHDL code has some FFI calls that aren't getting linked in) and then
>runs --bind for the sole purpose of knowing when ghdl -m failed for
>any other reason.
>
>Is this functionality actually missing (automatic …

Add bind only option (-b) to make command (-m).

---

doc/Invoking_GHDL.rst

Vim saw it for me, so I had to make a PR :-)

Typo severals -> several in Invoking doc

---

libraries/vendors/README.md
libraries/vendors/compile-altera.sh
libraries/vendors/compile-lattice.sh
libraries/vendors/compile-osvvm.sh
libraries/vendors/compile-vunit.sh
libraries/vendors/compile-xilinx-ise.sh
libraries/vendors/compile-xilinx-vivado.sh
libraries/vendors/config.sh
libraries/vendors/shared.sh

Hello,
here is the next part of reworked vendor library compile scripts.
New features:
- Partial VHDL-2008 support for Xilinx ISE and Vivado libraries.
- Refectored reusable code into Bash functions.
- Generate GHDL outputs into the new directory structure -> lib/v93 / lib/v08 (See #69)
- Replaced `realpath` (Debian specific) with `readlink -f` (tested e.g. on Ubuntu).
- Added new CLI parameters:
- `--src` -> source folder
- `--out` -> output folder
- `--ghdl` -> ghdl binary directory
TODO:
- Use environment variables like `XILINX` to auto-detect the Xilinx installation directory.
- Search vendor libraries in default installation directories, e.g. in `/opt/...`.
- Translate all Bash-Script improvements back to PowerShell.
@cclassic Please check, if the changes made for Lattice Diamond …

Reworked vendor library compile scripts for Altera, Lattice and Xilinx as well as OSVVM and VUnit.

---

libraries/vendors/README.md
libraries/vendors/compile-altera.sh
libraries/vendors/compile-lattice.sh
libraries/vendors/compile-osvvm.sh
libraries/vendors/compile-vunit.sh
libraries/vendors/compile-xilinx-ise.sh
libraries/vendors/compile-xilinx-vivado.sh
libraries/vendors/config.sh
libraries/vendors/shared.sh

Hello Tristan,
please merge this already squashed commit as a normal merge. Let's see what happens to the Git tree and merge history ... :).
Changes:
- Fixed minor issues (see #85), so Markus can test it again.
- Some scripts test for existing environment variables of vendor tools.
- Implemented a default installation directory guessing 'algorithm'.
- `--ghdl` refers to the GHDL executable not the binary directory.
Can you prepare an empty *.rst file (maybe with headline and a placeholder text),
where I could add the documentation for these scripts?
Regards
Patrick

Compile scripts: Implemented a default installation directory guessing

---

libraries/Makefile.inc
src/ghdldrv/ghdllocal.adb
testsuite/gna/bug028/testsuite.sh

This PR changes:
- `libraries/Makefile.inc`:
- New constants and rules for a synopsys flavor in VHDL-2008
- Enabled VITAL2000 for VHDL-2008 (is was a FIXME note)
- Analyze VITAL2000 in VHDL-2008 with `-frelaxed-rules`
- `ghdllocal.adb`:
- Removed synopsys check in VHDL-2008 mode.
This should help to solve #86.
Regards
Patrick

Synopsys flavor for VHDL-2008

---

src/ghdldrv/ghdllocal.adb
src/grt/Makefile.inc
src/ortho/mcode/ortho_code-x86-flags_windows64.ads

**The PR changes:**
- Fixed a directory separator check
*It was already implemented, but not applied to all existing checks. Are there other source lines, which might be missed?*
- Extended the sed rule to clean up the `grt.lst` file. Now it also removes `*.o` files with `.\`.
- Fixed `Flags.M64` for Windows x86_64
**This PR solves:**
- issue #104: sub-issue 3 (false `-o` option passing to `ghdl1-llvm.exe`)
- issue #105: sub-issue 1 (unknown op-codes in mcode for MinGW64)
**Unsolved issues:**
- issue #102: sub-issue 3 (unusual termination causing an Ada runtime message)
**New issues:**
- issue #110: `ghdl.exe -r testbench` can not execute `testbench`, because the file extension `*.exe` is missing

More changes for MinGWxx and LLVm backend

---

NEWS
README.md
dist/mcode/winbuild.ps1
libraries/ieee/README.ieee
libraries/ieee2008/README.ieee
src/ghdldrv/ghdlprint.adb
src/grt/fst/lz4.c
src/grt/fst/lz4.h
src/vhdl/iirs.ads
testsuite/gna/testsuite.sh
testsuite/gna/ticket89/x_ieee_proposed/src/README

Looking to make drive-by contributions, I noticed that there are a lot of `http://...` links that easily could be replaced by `https://...` links, which are usually deemed "safer".
As you might have objections to the reliability of certain hosts to stick with https, this path is split up by hostname.  I manually verified each unique URL to work properly.
Finally, there are a few links which are now invalid: see the last commit for that, which marks the dead links as such:
- The lz4 repository seems to now live at [https://github.com/Cyan4973/lz4]. so I'll contact upstream about getting that fixed eventually.
- I have no idea where the `vhdl.org` might have gone
This is the command I have grown while searching for non-`https` links:
```
grep -nrF http: . | grep -vF '//ghdl.free.fr' | grep …
```

Clean up links, repository-wide

---

dist/mcode/winbuild.ps1
dist/mcode/windows/compile-ghdl.ps1
dist/mcode/windows/compile-libraries.ps1
dist/mcode/windows/shared.psm1
dist/mcode/windows/targets.psm1
libraries/vendors/compile-altera.ps1
libraries/vendors/compile-lattice.ps1
libraries/vendors/compile-osvvm.ps1
libraries/vendors/compile-vunit.ps1
libraries/vendors/compile-xilinx-ise.ps1
libraries/vendors/compile-xilinx-vivado.ps1
libraries/vendors/shared.psm1

Hello,
here are the latest reworks for the Windows compile flow with PowerShell.
**This commit changes:**
- Removed `-InstallPath <Path>` -> `-Install [<Path>]` is enough
- Uses internal help pages like the user compile scripts
- Steps can be run as a group e.g. `-Compile` or as single tasks, e.g. `-Clean_GHDL -Compile_GHDL`
- Improved error reporting
- `filter.exe` is no longer needed and build on Windows  
It got replaced by PowerShell commands and act like the original `sed` commands in `Makefile`.
- The zip-file is created with a version number and back-end name. (`-CreatePackage -Zip`)
**Known issues:**
- Some lines are printed in verbose mode, even if `-Verbose` is disabled
- Installing GHDL in `PATH` is broken -> disabled  
I need to rewrite the functions for setting/removing paths …

Reworked compile scripts for Windows.

---

libraries/Makefile.inc

The objects from IEEE_SRCS were looked while
objects from IEEE08_SRCS were built.
Signed-off-by: David Keller <david.keller@enyx.fr>

Fix synopsys V08 library that was missing std_logic_1164-body.o.

---

BUILD.txt

Suggest the use of GCC's download_prerequisites for setting up gmp, mpfr, mpc
directly in the source tree. This is actually GCC's recommended way of
getting them (see https://gcc.gnu.org/wiki/InstallingGCC).

Simplifying build instructions for GCC backend

---

dist/mcode/winbuild.ps1
dist/mcode/windows/compile-ghdl.ps1
dist/mcode/windows/compile-libraries.ps1
dist/mcode/windows/shared.psm1

This commit fixes the premature module unloads for `shared` and `targets`.

Windows Build Flow: Fixed error of premature module unload.

---

dist/mcode/winbuild.ps1
dist/mcode/windows/compile-ghdl.ps1
dist/mcode/windows/compile-libraries.ps1
dist/mcode/windows/shared.psm1

Hello Tristan,
this PR should fix the verbosity problem in the Windows compile flow.
**Normal usage:**
```PowerShell
cd dist\mcode\
.\winbuild.ps1 -Clean
.\winbuild.ps1 -Compile
.\winbuild.ps1 -Install "C:\Tools\GHDL\0.34dev"
.\winbuild.ps1 -Clean -Compile -Install "C:\Tools\GHDL\0.34dev"
```
**Further features:**
* Verbosity can be controlled with the build-in options: `-Verbose` and `-Debug`.
* Single targets can be selected:
* `-Clean_GHDL` / `-Clean_Libraries`
* `-Compile_GHDL` / `-Compile_Libraries`
* Packaging:
* `-CreatePackage -Zip`
Kind regards
Patrick

Fixed verbosity problem in the Windows build flow.

---

dist/mcode/winbuild.ps1

Hello,
this PR fixes the long time intended behavior to add/remove GHDL from `$env:PATH`.
While installing, the script asks if GHDL should be registered in PATH (at machine level). The default is yes.
`Install GHDL in PATH at machine level? [Y/n]:`
GHDL gets removed from all levels (machine, user, session) while uninstalling.
Is this behavior ok?

winbuild: Fixed add and remove from PATH.

---

.gitignore
dist/mcode/winbuild.ps1
dist/mcode/windows/compile-ghdl.ps1
dist/mcode/windows/compile-libraries.ps1
dist/mcode/windows/targets.psm1

Hello,
this pull request:
* removes `Restore-PatchedVersionFile`
* adapts `Invoke-PatchVersionFile`
* add `version.ads` to `.gitignore`
* improves output formatting
* GHDL can be installed into PATH at: system, user or session level
This PR fixes issues after 	de1c213c36101c80f961f2ba24d4188646de8cb5.

Winbuild: Fixed Windows build flow after makefile changes.

---

dist/mcode/winbuild.ps1
libraries/vendors/compile-altera.ps1
libraries/vendors/compile-lattice.ps1
libraries/vendors/compile-osvvm.ps1
libraries/vendors/compile-vunit.ps1
libraries/vendors/compile-xilinx-ise.ps1
libraries/vendors/compile-xilinx-vivado.ps1
libraries/vendors/shared.psm1

This PR changes:
* Fixed a bug while updating an installation on Windows.
* The "vendors" directory was nested instead of replaced.
* Added verbosity control for vendor compile scripts.
* Removed trailing backslashes from input paths.
* Prepared to add a compile script for [UVVM_Utility_Library](https://github.com/UVVM/UVVM_All?ts=2)

Added verbosity control for vendor compile scripts.

---

libraries/vendors/compile-osvvm.ps1
libraries/vendors/compile-osvvm.sh

**This pull request:**
* Updates compile-osvvm.ps1/sh to add [OSVVM's](https://github.com/JimLewis/OSVVM) new [scoreboard](https://github.com/JimLewis/OSVVM/blob/master/ScoreboardGenericPkg.vhd?ts=2) packages.
-----------------------
:warning: The Scoreboard instance package for an [integer based scoreboard](https://github.com/JimLewis/OSVVM/blob/master/ScoreboardPkg_int.vhd?ts=2) causes an internal error reported as issue #197 .

Added OSVVM's new Scoreboards to the file list in compile-osvvm.ps1/sh.

---

libraries/vendors/compile-xilinx-ise.sh
libraries/vendors/compile-xilinx-vivado.sh

This pull request:
- Fixes a bug introduced by falsely using Bash syntax.
- If a `vhdl_analyze_order` file is provided, the scripts will use them now instead of `ls .../*.vhd` commands.
- Adds support for the unifast library in `compile-xilinx-vivado.sh`.

Bugfixes for compile-xilinx-***.sh scripts.

---

dist/mcode/windows/compile-libraries.ps1
libraries/vendors/compile-osvvm.ps1
libraries/vendors/compile-osvvm.sh

@JimLewis released [OSVVM 2016.11](https://github.com/OSVVM/OSVVM/tree/2016.11?ts=2). It comes with new VHDL 2008 packages. So the compile order needs an update. The next release or an intermediate release will contain a `compiler_order` file as used by e.g. Xilinx. With this file, both pre-compile scripts will be independent of file list and ordering changes.
**This pull request changes:**
* Updated compile order and file list for OSVVM pre-compilation scripts.
---------------
**Related issues:**
* OSVVM
* [Can OSVVM provide a "vhdl_analyze_order" file?](https://github.com/OSVVM/OSVVM/issues/19?ts=2)

Updated compile order in compile-osvvm.* files.

---

src/vhdl/translate/trans-chap9.adb
testsuite/gna/issue228/tb.vhdl
testsuite/gna/issue228/testsuite.sh

It closes #228.
Nothing is displayed unless the user specifies a report statement.
Testcase added to check this behaviour.

removing PSL coverage hit default report

---

dist/travis-ci.sh

The proposed modification behaves equally if an argument is passed. However, it does not overwrite `$BLD` if no argument is passed, so that it can be previously defined.
In fact, it is previously defined in the three builds declared in the [.travis.yml](https://github.com/tgingold/ghdl/blob/master/.travis.yml).

Allow not to pass `$BLD` as argument to <travis-ci.sh>

---

Makefile.in

The target **install.libghdlsynth** was missing in the Makefile file, so the command make install.libghdlsynth did not work when following the instructions for building ghdlsynth

target install.libghdlsynth added

---

dist/windows/InstallerTemplate.ps1
dist/windows/compile.ps1

Hello,
this pull request:
* Add a new option to `compile.ps1` to create a self-extracting PowerShell script.
```
cd GHDLRoot
.\dist\windows\compile.ps1 -Clean -Compile
.\dist\windows\compile.ps1 -Package -Zip
.\dist\windows\compile.ps1 -Package -PS1
```
(All command can be combined into one call.)
* Adds a template file `InstallerTemplate.ps1` which is used to create the installer.
**How does it work?**
1. Creating the installer:
1. GHDL is compressed in a ZIP file with preserving directory structure.
2. The ZIP file is read from disk and base64 encoded (2.2 MiB => 6 MiB)
3. A prepared template file is filled with the base64 string and saved.
4. The installer can be deployed (e.g. via GitHub releases)
2. Using the installer:
1. The user downloads the *.ps1 file.
2. The user executes …

Self-extracting PowerShell scripts as an installer alternative.

---

libraries/vendors/compile-uvvm.ps1
libraries/vendors/compile-uvvm.sh

UVVM 2.0.3 has changed filesets for entities and packages.
**This pull request changes:**
* Added entity `ti_uvvm_engine` to library `uvvm_vvc_framework`.

Precompile UVVM: Added ti_uvvm_engine to library uvvm_vvc_framework.

---

src/grt/ghwdump.c
src/grt/ghwlib.c
src/grt/ghwlib.h

ghwdump is sometimes useful beyond debugging .ghw files
For example, it can be used to implement external unit testing of a vhdl module by dumping a set of signals post-sim and checking with some other utility that some global properties of the set of dumped signals do hold true.
The current version of ghwdump -s dumps *all* signals, which, for a complex circuit can be very slow.
This patch adds a "-f" flag which lets the user choose which signals are dumped.
Example:
ghwdump -s -f 10 wave.ghw    # Dump only signal number 10
ghwdump -s -f 1-32,15,23-40  # Dump signal 1 to 32, signal 15, signals 23 to 40 (for ranges, bounds are included)

Add mechanism to restrict signals dumped by ghwdump

---

src/vhdl/sem_specs.adb

I found a (very) minor spelling error while debugging. Here is a fix!

Fix spelling error: declarared => declared

---

src/grt/ghwdump.c
src/grt/ghwlib.c
src/grt/ghwlib.h

Add new switch -H to ghwdump.
This is very similar to -h (dump hierarchy) except that full the signal pathname in the hierarchy is printed instead of just the signal name, and indentation is removed.
This is useful when doing batch processing on a ghw file to figure out the id of a bunch of signals that might not have unique terminal names in the hierarchy.
The pathname is in a format compatible with the file respectively read and written by the --read-wave-opt and --write-wave-opt options of ghdl.
Example current output with -h:
```
ghwdump -h waves.ghw
...
instance lfsr:
port-in clk: std_logic: #1
port-in rst: std_logic: #2
port-in off: std_logic: #46
port-in seed: std_logic_vector (31 downto 0): #47-#78
port-out val: std_logic_vector (31 downto 0): #79-#110
signal s0: std_logic_vector …
```

Add -H to ghwdump to dump full pathnames of signals

---

dist/windows/mcode/binary_file-format.ads
dist/windows/mcode/default_pathes.ads
dist/windows/mcode/grt-backtraces-impl.ads

**This PR fixes:**
* the PowerShell based build flow
**It changes:**
* added 3 missing files in `dist\windows\mcode`
* binary_file-format.ads
* default_pathes.ads
* grt-backtraces-impl.ads
**Required changes by @tgingold:**
* add appropriate file headers

Fix PowerShell based build flow

---

dist/windows/compile-libraries.ps1
dist/windows/shared.psm1

Hello Tristan,
**this PR changes:**
* Added GHDL's version filter pragmas to std_logic_misc.
* Disable overloaded functions for `std_logic_vector` and their bodies.
* Drive
* Sense
* AND_REDUCE
* NAND_REDUCE
* OR_REDUCE
* NOR_REDUCE
* XOR_REDUCE
* XNOR_REDUCE
* Added `std_logic_misc` for all VHDL versions to the synopsys flavor.
* Fixed an issue in Format-VHDLSourceFile.
* Changed source file sets in `Makefile.inc`
**This PR doesn't fix entirely:**
* Makefile.inc
* A `sed` filter for `!V08` and `START-!V08` is missing
* I can not really see when and where to apply the sed rules to create the filtered files before analyze
So please do the needed changes for Makefile.inc and sed before merging. The Windows compile flow is already changed and working. If completed, this issue will fix issue …

Added GHDL's version filter pragmas to std_logic_misc.

---

configure

It passes the testsuite but as I'm not actively using ghdl I don't know if there are other possible problems not covered by the tests. Also not sure what `llvm_be` does...

Support LLVM 5.0

---

.travis.yml

This PR just uses travis' built-in matrix expansion to slightly reduce the verbosity of `.travis.yml`. The produced jobs are the same:
- Before: https://travis-ci.org/1138-4EB/ghdl/builds/315555203
- After: https://travis-ci.org/1138-4EB/ghdl/builds/315562326

use travis matrix expansion

---

doc/getting/Releases.rst

Coherently with the tables posted in #486.
It also removes the ref to an unexisting 'release' branch. Instead, ZIP and TGZ variants of the master archive are provided.
Before: http://ghdl.readthedocs.io/en/latest/getting/Releases.html
After: http://ghdl-devfork.readthedocs.io/en/doc-v0.35-shields/getting/Releases.html

update getting/Releases to v0.35

---

Makefile.in
configure

User convenience when building GHDL on FreeBSD.
With these patches, GHDL/LLVM can be built on FreeBSD 11.1 with:
```
$ mkdir build && cd build
$ ../configure --prefix=/opt/ghdl-0.35-llvm --with-llvm-config=/usr/local/llvm40/bin/llvm-config --with-gnatmake=/usr/local/gcc6-aux/bin/gnatmake
$ gmake
$ gmake install
```

Freebsd configure

---

libraries/vendors/compile-altera.ps1
libraries/vendors/compile-intel.ps1
libraries/vendors/compile-lattice.ps1
libraries/vendors/compile-xilinx-ise.ps1
libraries/vendors/compile-xilinx-vivado.ps1

Ran into an issue when compiling vendor libraries on Windows 7, decided to write a fix for it. Tested using the compile-xilinx-ise.ps1 script on Windows 7 with Powershell 4.0.
Error was:
```
Get-DriveInfo : The term 'Get-DriveInfo' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\craign\Documents\ghdl\libraries\vendors\compile-xilinx-ise.ps1:130 char:22
+         foreach ($Drive in Get-DriveInfo)
+                            ~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Get-DriveInfo:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
[ERROR]: Xilinx ISE is not configured in …
```

Remove dependency on Get-DriveInfo for powershell compile scripts

---

configure

This enables configure runs under Cygwin.
The patch also (re)moves an unused `` curdir=`pwd` ``.

configure: Fall back to `pwd` if `pwd -W` does not work

---

Makefile.in
configure

Running the testsuite under Cygwin got stuck at `testsuite/gna/issue450`.
First failure was a *File not found* when linking with `-lghdlvpi`. The first commit addresses that by making sure that `SOEXT=.dll` (and other Windows-like settings) under Cygwin.
The error then changed to *Permission denied*. That is addressed by the second commit which switches to `INSTALL_PROGRAM` for anything with `SOEXT`. This makes sure that DLLs get executable permissions. Note that this change affects all platforms: Looking into `/usr/lib` under Linux (`SOEXT=.so`) as well as under MacOS X (`SOEXT=.dylib`) I see that shared libraries should get executable permissions.
Running `testsuite/gna/issue450/testsuite.sh` can now load the module `vip2.vpi`.
(Thereafter it segfaults, and a `gdb` backtrace tells me …

Cygwin executable adaptations

---

.travis.yml

We are currently testing only `xcode7.3`. Travis supports `xcode6.4` to `xcode9.3`, the default being `xcode8.3`: https://docs.travis-ci.com/user/languages/objective-c/#Supported-Xcode-versions.
This PR adds `xcode8.3` and `xcode9.3` jobs to the travis matrix, just to test that all of them work. However, I think that we should choose one. 8.3? 9.3?

Update xcode version in travis

---

doc/building/PrecompileVendorPrimitives.rst
doc/ghdl.texi
libraries/vendors/README.md
src/bug.adb
src/grt/grt-lib.ads
src/grt/grt-main.adb
src/grt/grt-processes.adb
src/grt/grt-signals.ads
src/vhdl/sem_expr.adb
testsuite/gna/bug037/bugreport.txt
testsuite/gna/issue25/1_SecondaryUnit.vhdl
testsuite/gna/issue38/bugreport_aliasprotected.vhdl
testsuite/gna/issue42/bugreport_attribute.vhdl

This PR is to replace `occured` with `occurred`. I don't know why some blank lines are changed too.

fix 'occured' typo

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING
doc/contribute.rst
doc/shields.inc

As commented in #579, this PR adds 'Bug report' and 'Feature request' issue templates. After this is merged, when a user creates a new issue three options will be available: the two I mentioned and the regular one (empty). In the 'Bug report' template I added a reference to [1138-4EB/issue-runner](https://github.com/1138-4EB/issue-runner) and I provided a very basic example. Also:
- A 'Pull request' template is added.
- The docs are updated with new shields (`new bug report`, `new feature request` and `new pull request`).
- `CONTRIBUTING` is moved to `.github`, extension `.md` is added and the content is updated.

add .github (issue templates)

---

.github/ISSUE_TEMPLATE/bug_report.md

As suggested by @keesj in Gitter, this PR adds a `wait` statement to the `ent.vhd` example in the `bug_report.md` template.

add wait statement to bug_report reproduction example

---

src/ghdldrv/ghdlrun.adb
src/grt/grt-processes.adb
src/ortho/mcode/ortho_code-decls.adb
src/ortho/mcode/ortho_code-dwarf.adb
src/ortho/mcode/ortho_code-x86-abi.adb
src/ortho/mcode/ortho_code-x86-emits.adb
src/ortho/mcode/ortho_jit.adb

I had to remove some additional redundant use-clauses in order to get GHDL to compile with GCC 8.1. The compiled GHDL seems to work fine for me, but I'm not familiar with ADA or the GHDL internals so please review carefully for any breakage.
This is related to issue #568

Remove redundant use-clauses for gcc 8.1 compatibility

---

.github/ISSUE_TEMPLATE/bug_report.md

I had only tried the issue-runner on Windows hosts, where bind mount permissions are not so relevant. Today I tried it in Fedora and I realized that option `:z` must be used, because of selinux. This PR just adds it.
See https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label

add :z to the docker bind argument

---

.travis.yml

As commented by @CraigNoble in gitter, 2018-05-29 was the End-of-life for Fedora 26: https://en.wikipedia.org/wiki/Fedora_version_history#Version_history
This PR skips Fedora 27 and jumps to Fedora 28.

use fedora28 instead of fedora26

---

dist/travis/build.sh

When GHDL is built with GCC backend, and the target version of GCC is not the same as the version of the GCC used in the build, the process logs so heavily that the 4MB in travis-ci is reached. This results in the build being broken (see last two lines in https://api.travis-ci.com/v3/job/127969859/log.txt). Moreover, if all the make output is saved to a file, the build fails because no output is received in 10 minutes and travis thinks that it is stalled.
This PR logs stderr to a file (not stdout). When make is done, the last 1000 lines of the file are shown. This allows the build to finish successfully.

log stderr of make to a file and use tail to show last 1000 lines

---

libraries/vendors/compile-altera.sh

Quartus 13 is last version which supported older devices. Also first
supported version of script.
TODO: Port support to Windows, maybe add more file existence testing.
This patch adds support for older cyclone devices. It imports clean quartus version 13 and 17 sim_lib. 
--------------
Closes #303

Cyclone 1,2,3 support for compile-altera.sh

---

dist/travis/build.sh

ATM, LLVM 6.0 is supported in the main configure file in the root, but not in the travis build script.

add option llvm-6.0 to travis build script

---

dist/windows/InstallerTemplate.ps1

Fixes the installation process in vanilla PowerShell on Windows 10. Creates temporary zip file because Expand-Archive expects a file with .zip extension. Also call `Expand-Archive` with correct syntax (for bulitin PS version).
**Fixed issues**
* [PowerShell installation fail on Windows 10 (x64) [1803]](https://github.com/ghdl/ghdl/issues/678)
* [PowerShell installation failed](https://github.com/ghdl/ghdl/issues/457)

PowerShell Windows installation fix

---

dist/windows/appveyor/install.ps1

**Description**  
MinGW changed from `*llvm35` and `*clang35` packages to `*llvm` and `clang` packages.
This PR removes the version number for LLVM. Latest version used by MinGW is `7.0.0-1`.
This should fix #702.

Removed explicit llvm35 depdendency

---

.travis.yml
dist/travis/man.sh
dist/travis/travis-ci.sh

Close #622.
This PR adds a parallel job in the Travis matrix, to build man pages for GHDL. When a release is tagged, file `ghdl.1` is added to the release artifacts, so it is pushed to GitHub along with the tarballs for different distributions.
Even though the file is only pushed to GitHub when a release is tagged, the content can be seen in every Travis build. See e.g. https://travis-ci.org/1138-4EB/ghdl/builds/475993763 and https://travis-ci.org/1138-4EB/ghdl/jobs/475993771

Add man pages job to travis

---

.travis.yml

Follow up on #574. Related to #744.
Defaults in Travis CI are now macOS 10.13 and Xcode 9.4.1. See:
- https://docs.travis-ci.com/user/reference/osx/#macos-version
- https://blog.travis-ci.com/2018-07-19-xcode9-4-default-announce
> In order to streamline our image catalog, minor 9 versions other than xcode9.2 and 9.latest will be deprecated when 10.0 is released (date TBA). If you are using xcode9, xcode9.1 , and xcode9.3, please plan to move to xcode9.2 or xcode9.4 as soon as you are able.
This PR updates `.travis.yml` to use the default environment. as `xcode9.3` is being deprecated.

Update travis macos job to use xcode9.4 (current default)

---

.travis.yml

Ubuntu Xenial 16.04 is available as the base image in Travis: https://blog.travis-ci.com/2018-11-08-xenial-release. The default in Travis is still Ubuntu Trusty 14.04: https://docs.travis-ci.com/user/reference/overview/#linux. However, switching to Xenial is recommended for users coming from some deprecated virtualization environments: https://docs.travis-ci.com/user/reference/overview/#deprecated-virtualization-environments.
Both 14.04 and 16.04 are LTS releases. Although 14.04 is not deprecated yet, the Enf of Life (EOL) is scheduled for april: https://www.ubuntu.com/about/release-cycle. Therefore, we can expect Travis to switch the default from trusty to xenial in Q3 (see https://blog.travis-ci.com/2017-04-17-precise-EOL and https://docs.travis-ci.com/user/precise-to-trusty-migration-gu …

Update travis dist from trusty to xenial

---

dist/macosx/install-ada.sh
dist/travis/travis-ci.sh

This is just some style change. On the one hand, execution of `install-ada.sh` is moved before section *Build*. This is more coherent with other platforms, where dependencies are already available when entering section *Build*. On the other hand, multiple calls to `rm` are put together.
> NOTE: this slightly affects the references in #744.

style: install-ada

---

src/grt/grt-vpi.adb
src/grt/grt-vpi.ads

The changes enable `vpi_get(vpiType, handle_to_port)` to return `vpiPort` if the signal is a port. It also enables `vpi_get(vpiDirection, handle_to_port)` to return correct port directions(`vpiInput`, `vpiOutput`, or `vpiInout`).
The changes does not change behavior for other types of signals.
:rotating_light: Before submitting your PR, please read [contribute](http://ghdl.readthedocs.io/en/latest/contribute.html#fork-modify-and-pull-request) in the [Docs](http://ghdl.readthedocs.io/en/latest/index.html), and review the following checklist:
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did, what …

VPI: add support for detecting ports and their directions

---

doc/requirements.txt

At the moment, if the documentation is built outside of RTD, the following error is shown:
``` bash
sphinx_rtd_theme is no longer a hard dependency since version 1.4.0. Please install it manually.(pip install sphinx_rtd_theme)
```
This PR adds the dependency to `requirements.txt`, so that it is automatically installed. For example:
``` bash
$(command -v winpty) docker run --rm -itv /$(pwd)://src -w //src/doc btdi/sphinx:py3-featured sh -c "\
pip install -r requirements.txt; \
sphinx-build -T -b html -D language=en . _build/html"
```

add sphinx_rtd_theme to requirements.txt

---

.readthedocs.yml

This PR updates `.readthedoc.yml` to version 2. See:
- https://blog.readthedocs.com/configuration-file-v2/
- https://docs.readthedocs.io/en/latest/config-file/v2
- https://docs.readthedocs.io/en/latest/config-file/v2#migrating-from-v1

update .readthedocs.yml to version 2

---

doc/build.sh
doc/conf.py
doc/exec.py
doc/getting/Releases.rst
doc/helpers.py
doc/requirements.txt

As commented in [#768](https://github.com/ghdl/ghdl/pull/768#issuecomment-466784776), this PR updates the `getting/Releases` section of the docs:
> * Current output: https://ghdl.readthedocs.io/en/latest/getting/Releases.html
> * New proposal: https://ghdl-devfork.readthedocs.io/en/doc-dynreleases/getting/Releases.html
>
> The most important enhancement is that the two tables ('Downloading pre-built packages' and 'Pre-built packages of older releases') are generated automatically at compile time after retrieving a JSON response from https://api.github.com/repos/ghdl/ghdl/releases.
A custom sphinx directive (`doc/exec.py`, see https://stackoverflow.com/questions/7250659/how-to-use-python-to-programmatically-generate-part-of-sphinx-documentation/18143318) is added, in order to allow …

doc: add custom directive 'exec', generate releases shields and tables with json data retrieved from github api

---

dist/travis/build.sh

This PR forces `-fPIC` to be used when building GHDL, which involves all the libraries in `$prefix/lib/*`. This is required in order to compile VHDL sources to C objects that can then be used to build foreign applications: https://github.com/ghdl/ghdl/issues/640#issuecomment-418470167.
I don't know if this is the best solution for the problem I am trying to solve. I'd be open to any suggestion to avoid making this a fixed setting. However, I am unsure about how to pass this option when calling either `configure` or `make`.

Build GHDL and libs with -fPIC

---

src/synth/synth-stmts.adb
src/vhdl/simulate/simul-execution.adb
src/vhdl/simulate/simul-simulation-main.adb

When following the instructions at https://github.com/tgingold/ghdlsynth-beta, compilation of the libghdlsynth.so target failed for me because of gnat warnings being treated as errors.
These errors all boiled down to 'use' or 'with' clauses that were considered being 'without effect', therefore this PR removes them.
This happens on a relatively up-to-date system using gcc/gnat 8.3.

Fix build for libghdlsynth.so targets with gcc/gnat 8.3

---

src/grt/grt.ver

Close #800 and Close #640.
As commented in #800, this PR adds a version (`ANY`) to `grt.ver`, so it is possible to add other visible symbols to the binary generated with `ghdl -e [args] -Wl,-Wl,--version-script=custom.ver`.

add some version to grt.ver (#800)

---

Makefile.in

I didn't dive into the details, but it happens that, during a regular build with `OPT_FLAGS="-fPIC" LIB_CFLAGS="-fPIC" ./dist/travis/build.sh -b llvm -p ghdl-llvm-fPIC`, the makefile in `src/grt/Makefile.inc` is executed twice. The first time, `GRT_FLAGS` is `-g`, and the second time `GRT_FLAGS` is `$OPT_FLAGS` (as expected after #670). In order to build binaries that are dynamically loadable (#803), it is required for `GRT_FLAGS` to always contain `-fPIC`.
Currently, externally defined variable `OPT_FLAGS` is not preserved when `"$(enable_checks)" "true"`. This PR changes it, so that it is always preserved. I applied the same change to ` ADA_FLAGS` and `LIB_CFLAGS`, although I didn't find it to be a requirement.

preserve externally set OPT_FLAGS, ADA_FLAGS and/or LIB_CFLAGS

---

Makefile.in
configure
dist/travis/build.sh
src/ghdldrv/default_paths.ads.in

Currently, GHDL can be built as:
``` bash
OPT_FLAGS="-fPIC" \
LIB_CFLAGS="-fPIC" \
./dist/travis/build.sh -b llvm -p ghdl-llvm-fPIC
```
Then, sources must be analyzed with `-fPIC` in order to generate a PIE binary. E.g., in VUnit:
```
ui.set_compile_option("ghdl.flags", ['-fPIC'])
ui.set_sim_option("ghdl.elab_flags", ['-fPIC', '-Wl,-pie'])
```
---
This PR allows to simplify the commands above to:
``` bash
CONFIG_OPTS="--enable-default-pie " \
./dist/travis/build.sh -b llvm -p ghdl-llvm-fPIC
```
and
``` python
ui.set_sim_option("ghdl.elab_flags", ['-Wl,-pie'])
```
I.e., if GHDL is built with `--enable-default-pie`, `-fPIC` is implicitly added (by default) to any `ghdl -a` or `ghdl -e` command.
This PR sets the default of variable `default_pie` in `configure` to `false`. It is enabled …

Add configure option '--default-pic' to enable '-fPIC' by default

---

Makefile.in

This PR extends the Makefile's `install` target to install the `std.standard` package VHDL source.
The `std.standard` package VHDL source is generated with `ghdl --disp-standard --std=<87|93|08>` and redirected to `$PREFIX/lib/ghdl/src/std/standard.v<87|93|08>`.
This fixes issue #802.
None

Install `std.standard` package VHDL source during `make install` phase

---

dist/travis/travis-ci.sh

Related to #805, this PR allows to pass CONFIG_OPTS to `travis-ci.sh`, which is then passed to docker containers. This will be used in ghdl/docker, so that all the ready-to-use docker images are built with `--default-pic`.

travis-ci: pass CONFIG_OPTS to docker containers

---

Makefile.in

See https://travis-ci.com/ghdl/docker/jobs/210330285
Maybe the rule itself can be removed, since generating a tarball for libghdl is not required now.

fix(makefile): conf.py does not exist anymore

---

doc/building/llvm/GNULinux-GNAT.rst
doc/building/llvm/index.rst

As commented in [#859](https://github.com/ghdl/ghdl/issues/859#issuecomment-509022726).
@tgingold, is it worth opening an issue to track debug support on versions >3.5?

doc: update list of supported LLVM versions

---

.travis.yml
dist/travis/build.sh
dist/travis/test.sh
dist/travis/travis-ci.sh
dist/travis/utils.sh

In this PR:
- Option `--synth` is added to `dist/travis/build.sh` and `dist/travis/test.sh`.
- A Debian Buster mcode job is added, where GHDL is buit with `--enable-synth` and the synth testsuite is executed.
- Fedora jobs are updated from 28 to 30.
- Debian jobs are updated from Stretch to Buster.

Add synth testsuite to CI

---

src/synth/ghdlsynth.h
src/synth/ghdlsynth_gates.h
src/synth/netlists-utils.adb
src/synth/netlists-utils.ads

To create a black box cell in yosys I need to get the width of the port. I don't think this is exposed in another way, so I added an utility function.
This change is required for https://github.com/tgingold/ghdlsynth-beta/pull/25
p.s. Somehow the gates were also outdated again, because when running make it added 3 new entries.

Add port width utility function for yosys

---

src/synth/netlists-builders.adb
src/synth/netlists-disp_vhdl.adb
src/synth/synth-context.adb
src/synth/synth-expr.adb

I have some code like the following that I'm trying to get to work
```vhdl
signal counter : integer range 0 to 63;
--[...]
if counter < 2 then
--[...]
counter <= counter - 1;
```
So first problem is that integer literals seem to be 64 bits.
The logic that makes `Const_UB32` just checks for the width and then fails.
But for small constants, it should be safe to use, so I changed the check to just check if the constant fits in 32 bits.
The next problem is that the comparison then tries to compare a 6-bit value with a 32-bit value, and gives an error. I am not sure how to resolve this, probably one of the values needs to be extended, or the literal needs to match the range. **UNSOLVED** So I changed my code to define constants with the correct range.
```vhdl
constant two : integer range 0 to …
```

Better support for ranged integers and integer literals.

---

libraries/Makefile.inc
libraries/openieee/upf-body.vhdl
libraries/openieee/upf.vhdl

Close #436.
Ref #888.
This PR is an update/rework of #436. As requested by @tgingold, the ieee and ieee2008 versions look the same, so sources are added once only. Furthermore, they are added to openieee. As a result, patching the makefile is not required.
/cc @tsailer

openieee: add dummy UPF package

---

src/synth/synth-stmts.adb
testsuite/synth/psl01/hello.vhdl

This adds support for synthesis of PSL assert and assume keywords, so they can be used in SimbiYosys formal verification.
This passes my little update to the testbench, but might very well break once I start to use it for real testing. I've also not added cover yet. So it's ok to merge, but I'll likely have more changes in the coming days.

Support for PSL assert and assume in synthesis

---

src/synth/synth-disp_vhdl.adb
src/synth/synth-expr.adb
src/vhdl/vhdl-ieee-numeric.adb
src/vhdl/vhdl-nodes.ads
testsuite/synth/psl01/hello.vhdl

This makes it so you can do logic operators on `unsigned` ans `signed` without an explicit cast.
I'm not sure if there is any meaning in having them as separate IIR, but it's what the rest of the code does too.
I don't think we're handling mixed `signed` and `unsigned` operations, but who in their right mind does that anyway.
Example:
```vhdl
entity alu is
port (
a : in unsigned(7 downto 0);
b : in unsigned(7 downto 0);
y : out unsigned(7 downto 0)
);
end alu;
architecture rtl of alu is
begin
y <= a and b;
end rtl;
```
p.s. I accidentally committed a change to the psl testcase. I can revert and make a new pr for that if it bothers you. I don't even think `hello.vhdl` is used any more.

add synthesis support for logic operators on numeric types

---

src/synth/netlists-disp_vhdl.adb
src/synth/synth-disp_vhdl.adb
src/synth/synth-expr.adb
src/vhdl/vhdl-ieee-std_logic_1164.adb
src/vhdl/vhdl-nodes.ads
testsuite/synth/unary01/test.vhdl
testsuite/synth/unary01/testsuite.sh

In VHDL-2008 there is support for unary logic operations, stuff like `and foo`. This was already supported in the parser and used in synthesizing PSL assumptions, so now I connected the dots.
For now it only supports AND/OR on std_logic_vector. I'll add support for signed/unsigned and xor and other operations later. Probably after dinner :)

Support for 2008 unary reduce operators

---

src/vhdl/translate/trans-chap9.adb
src/vhdl/translate/trans-rtis.adb

Code that includes a PSL restrict derivative currently synthesizes perfectly, but crashes in simulation with a `cannot handle IIR_KIND_PSL_RESTRICT_DIRECTIVE`. This PR simple makes them a no-op in various places.

ignore restrict in simulation

---

src/synth/synth-expr.adb
testsuite/synth/int01/int_operators.vhdl
testsuite/synth/int01/testsuite.sh

This PR implements two missing integer operators for synthesis, i. e. `inequality` and `remainder`.

Integer operators

---

Makefile.in

Add missing directory now that llvm backend enables the synth feature.

fix llvm build with synth enabled

---

README.md

Just a couple of minor fixes that I forgot in #906:
- References to section 'Building' in the docs now have a different URL.
- ghdlsynth-beta now uses `libghdl` instead of `libghdlsynth`.

readme: fix refs to 'Building'

---

configure

On Windows (MSYS/MINGW), building after cloning the repo fails because `python/libghdl/version.py` is automatically converted to CRLF (as all other files in the repo). This PR 'fixes' the check with `cmp` in configure, so that as many bytes as the length of `ghdl_version` are compared only.

fix(configure): ignore line ending when comparing ghdl_version and libghdl_version

---

configure

This PR contains several fixes for 'configure':
- A comment is added, as suggested in #910.
- Indentation mixes tabs and spaces. It is normalized to 2 spaces.
- On MSYS2/MINGW I was getting errors because of mistaches between `srcdir` and `abs_srcdir`. One of the underlying issues was that `cmp` was not available. I added a check to print a better error message.
- On MSYS2/MINGW, `$OS` is set to `Windows_NT`. Currently, configure forces MSYS2/MINGW to use Windows paths. I fixed it so that `pwd` is used. This is required in order to execute `configure` successfully in GitHub Actions jobs.

Fix configure

---

configure

One of the commits in #911 was not required, and does produce a failure with LLVM backend for MINGW64. This reverts commit 7b02418ec508af9e340cad5e93ab06e8f1fb84c8.
With this fix, the migration from Travis CI and AppVeyor to GitHub Actions is almost ready: https://github.com/1138-4EB/ghdl/commits/actions. See example run: https://github.com/1138-4EB/ghdl/runs/209700424. We need to decide the new distribution scheme, tho (#888).

revert "configure: fix setting abs_srcdir on MSYS2/MINGW" (#911)

---

testsuite/sanity/005examples/testsuite.sh

This is a work around #915 until we guess how to properly move the examples out of `doc`.

fix: skip testsuite/sanity/005examples when 'doc' not found

---

src/synth/ghdlsynth_gates.h
src/synth/netlists-builders.adb
src/synth/netlists-builders.ads
src/synth/netlists-disp_vhdl.adb
src/synth/netlists-gates.ads
src/synth/synth-stmts.adb
testsuite/synth/psl01/cover1.vhdl
testsuite/synth/psl01/cover2.vhdl
testsuite/synth/psl01/testsuite.sh

As mentioned in https://github.com/ghdl/ghdl/issues/927 here is my first pull request to implement support for PSL cover directives with synthesis. I added two test cases to check the additions.
I'm not sure about the change in `src/synth/ghdlsynth_gates.h`as the file header says to not modify that file, as it is generated. I can remove that change if necessary.
@tgingold please check and comment if there are problems with the PR. And thanks for your suggestions.

synth: Add support for PSL cover directive

---

src/synth/synth-oper.adb

This PR adds handling of comparing two signed vectors, for example:
```vhdl
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
entity test is
port (
a, b  : in  signed(7 downto 0);
eq   : out std_logic
);
end entity test;
architecture rtl of test is
begin
eq <= '1' when a = b else '0';
end architecture rtl;
```
Without this addition, we got an error like 
`synth_dyadic_operation: unhandled IIR_PREDEFINED_IEEE_NUMERIC_STD_EQ_SGN_SGN`
With the addition, this compare is mapped to `Id_Eq`. I would like to add compare of signed to Integer also, but for that a new function `Synth_Sresize (Val : Value_Acc; W : Width; Loc : Node)` is needed which isn't that trivial (for me ;)).

synth: add support for comp. equal of two signed

---

src/synth/synth-stmts.adb

Currently GHDL can synth a `wait` statement only if it is the first statement in a process and has a clock condition. This PR just adds a check that there is an actual condition.
#903: The latest Microwatt uses a `wait` without condition at the end of a debug process. Not sure if this should be supported and how.

Show error on wait without condition

---

Makefile.in

In PR #811, the `install` target of the `Makefile` got enhanced to install the VHDL sources of the `std.standard` along with the other VHDL sources of the standard packages. Sometime over the past month, the installation location for the VHDL sources of the standard packages got changed. This PR adjusts the install paths for the `standard.vhdl` files to `lib/ghdl/src/std/v??/standard.vhdl`.
This PR is related to PR #811 and issue #802, which facilitate using the `rust_hdl` language server for VHDL.
None.

Install source of std.standard package to correct version sub-directory

---

doc/references/ImplementationOfVHDL.rst

This is a work in process of enhancing the documentation of PSL support.
Changes are made to the PSL section under:
IMPLEMENTATION REFERENCES -> Implementation of VHDL -> Implementation of PSL.
You can see the result on the [Read the docs](https://ghdl-tmeissner.readthedocs.io/en/latest/references/ImplementationOfVHDL.html#psl-support) page of my fork.
@1138-4EB, @tgingold & others: hints and tips are welcome :)

Enhance documentation of PSL support

---

doc/examples/quick_start/DLXModelSuite.rst
doc/examples/quick_start/README.rst
doc/examples/quick_start/adder/README.rst
doc/examples/quick_start/heartbeat/README.rst
doc/examples/quick_start/hello/README.rst
doc/using/CommandReference.rst
doc/using/Foreign.rst
doc/using/ImplementationOfVHDL.rst
doc/using/ImplementationOfVITAL.rst
doc/using/InvokingGHDL.rst
doc/using/Simulation.rst

As suggested by @Paebbels ([November 12, 2019 12:55 AM](https://gitter.im/ghdl1/Lobby?at=5dc9f4f635889012b1efe572)), `.. program:: ghdl` directives that were removed in #1003 are added again.

doc: add '.. program:: ghdl' directive

---

dist/travis/travis-ci.sh

The name of the envvar that is checked to decide whether to run the synth test suite is not correct. `ISEXTRA` is checked, and it should be `EXTRA`. As a result, currently issues with the synth test suite are not being checked: https://travis-ci.org/ghdl/ghdl/jobs/614170911#L1270
Actually, this PR fails because there is currently some issue with `master`: https://travis-ci.org/1138-4EB/ghdl/jobs/614291974#L1836

ci: fix envvar name to run synth tests

---

libraries/vendors/compile-uvvm.sh

Wishbone VIP is located in [UVVM_Community_VIPs](https://github.com/UVVM/UVVM_Community_VIPs) repository. To compile it needs to be copied to [UVVM](https://github.com/UVVM/UVVM) directory. Why and how is explained in this issue [UVVM_Community_VIPs issue 2](https://github.com/UVVM/UVVM_Community_VIPs/issues/2).
When it is not copied, and you compile with `--all` flag, compilation of standard VIPs from [UVVM](https://github.com/UVVM/UVVM) repository success, so this commit does not break anything.

Add option for compiling Wishbone VIP for UVVM framework.

---

dist/man.sh
doc/make.sh

The names of images that are used in `man.sh` and `make.sh` changed. This PR fixes them so that job 'man' in Travis is not broken.

fix btdi image names

---

dist/macosx/install-ada.sh

Apparently, AdaCore changed the URLs of the tarballs, and osx builds are failing, unless GNAT GPL is already cached in the CI system. This PR updates the URL to fix it. I had to use `wget` instead of `curl`, because I couldn't guess how to make the latter work.

fix gnat-gpl download URL (osx)

---

.github/workflows/push.yml
.travis.yml
dist/ci-run.sh
dist/macosx/install-ada.sh

Close #1071 
This PR contains a few non-critical updates to the macOS environments in CI:
- GNAT GPL is updated to 2019. Unlike 2017, this version is only available as a DMG file, not as a tarball. Hence, `7z` is used to extract it, instead of `tar`.
- Xcode in Travis is updated to 10.
- Instead of executing the installation of GNAT GPL in the ci run script, it is done in the YAML files of the CI services. The motivation for this is that it is a dependency that is required in the system, rather than a piece of GHDL. On other platforms, dependencies are handled outside of the build scripts.

ci: update installation of GNAT GPL on macOS

---

src/synth/netlists-disp_vhdl.adb

I hit an issue with vhdl that uses divides when using `ghdl --synth`.

netlists: Handle sdiv and udiv

---

dist/ci-run.sh

It seems that tags in GCC's mirror at GitHub were renamed, which broke our CI job. This PR fixes it. By the way, `codeload.github.com` is used.

ci: the URL to retrieve GCC sources has changed

---

doc/development/Documentation.rst
doc/development/GSOC.rst
doc/development/Roadmap.rst
doc/using/Foreign.rst

A subsection named 'GSOC Ideas' is added to 'Roadmap | Future Improvements'. I gathered GHDL-related projects that were proposed under the umbrella of FOSSi foundation on 2017, 2018 and 2019. I added some other myself. Last, I searched for related issues and referenced them in each idea, to hopefully make it easier for interested contributors/students to understand the context.

doc: add 'GSOC Ideas'

---

.travis.yml

This PR updates docker images used in Travis from Ubuntu 14 to Ubuntu 16 and from Fedora 30 to Fedora 31.

travis: update to ubuntu16 and fedora31

---

Makefile.in
dist/ci-run.sh

Currently, GHDL is built in CI jobs by setting `prefix`|`--prefix` to a local subdir (`./install-<BACKEND>`):
https://github.com/ghdl/ghdl/blob/501193da2ca0f6ad0f5c514eb793a7e3a3224887/dist/ci-run.sh#L251
In ghdlsynth-beta, instead of setting `prefix`, it defaults to `/usr/local` and `DESTDIR` is used:
https://github.com/tgingold/ghdlsynth-beta/blob/910073d647e55d133494429d8c3a4bacffc32428/ci.sh#L36-L38
Since GHDL is built daily with `--enable-synth` in ghdl/docker (see https://github.com/ghdl/docker/actions?query=workflow%3Adaily), I think it'd be good to reuse image `ghdl/pkg:buster-mcode`. That would reduce the CI job of ghdlsynth-beta to building `ghdl_yosys.so` and running the tests.
Unfortunately, `ghdl_yosys.so` looks for GHDL in the `prefix`. As a result, it fails when searching …

use DESTDIR instead of --prefix

---

Makefile.in
doc/getting/GCC.rst

No change has been required for ortho-lang-9.c so I have solved it this way. Build-tested only so far.

update for gcc10

---

src/grt/config/jumps.c

This PR disables backtrace on Android, since that feature is not included in the Bionic C library. This allows to follow a regular build procedure to have GHDL available on smartphones and tablets!

disable backtrace on android

---

dist/termux.sh

Ref #1142
In this PR, a shell script to install dependencies, build GHDL and install GHDL on [termux](https://termux.com/) is added to subdir `dist`.
<p align="center"><img src="https://user-images.githubusercontent.com/38422348/74899270-aff08300-539c-11ea-8f25-4e168fd4c739.png" alt="ghdl_termux" width="200"/></p>
Notes:
- GCC and GNAT are not available in the main repo, so its-pointless' repo is used (see https://github.com/its-pointless/gcc_termux).
- In the future, setting symlinks explicitly might not be required (see its-pointless/gcc_termux#84).
- Due to constraints regarding shebangs (see https://wiki.termux.com/wiki/Differences_from_Linux#Termux_is_not_FHS_compliant), this script should be execute explicitly: `bash dist/termux.sh`.
- The default `$PREFIX` is relevant (NOT empty, …

add build script for termux

---

dist/termux.sh

Now that its-pointless/gcc_termux#84 is fixed, some symbolic links don't need to be created explicitly.

termux: setting symlinks explicitly is not required now

---

python/vhdl_langserver/workspace.py

On Windows, a URI has to begin with file:/// (3 slashes!).
Now, the correct implementation from lsp.py is used to create the URIs.

python: fix document URI creation on Windows

---

configure
doc/getting/LLVM.rst

Add compatibility with LLVM-10 to the configure script, and update documentation.
The build has been tested on Fedora 33 / Rawhide: https://koji.fedoraproject.org/koji/taskinfo?taskID=43022894

Add compatibility with LLVM-10.

---

src/grt/ghdl_main.adb
testsuite/gna/issue1206/main_notnull.c
testsuite/gna/issue1206/testsuite.sh

The fix fox #1206 applied in https://github.com/ghdl/ghdl/commit/7a211109152e82843a59ba70b0a080ce91b9b495 was required because it had been broken in https://github.com/ghdl/ghdl/commit/2fc3356ae0d34dae87eb22c94f4b5eaa1873695b 10 days ago. The behaviour now is the same that it was for 15 years.
However, I think it is not completely correct. The underlaying issue is not argc being zero, but argv being null. Currently, if `argc=0` and `argv={"progname"}`, GHDL will ignore `progname`, set it to `null` and use `Default_Progname` instead. This PR changes it so that `Argv(0)` is preserved if `Argv/=null`.
BTW, I replaced:
```sh
$CC -c main.c
analyze hello.vhdl
elab -Wl,main.o hello
```
with
```sh
analyze hello.vhdl
elab -Wl,main.c hello
```
@tgingold, is there any relevant difference between …

grt: handle argc=0 and argv/=null in ghdl_main (#1206)

---

dist/msys2-mingw/run.sh
doc/using/InvokingGHDL.rst
testsuite/testenv.sh

As discussed in #1278, the current `sed` command in `testenv.sh` does not work on GHA Windows jobs, because the drive is not `C:`. This PR changes `--vpi-library-dir` to `--vpi-library-dir-unix`. At the same time, the workaround that existed in `dist/msys2-mingw/run.sh` is removed.
By the way, `--vpi-library-dir-unix` is added to the docs, and some redundant headers are removed.

Document and use --vpi-library-dir-unix

---

src/vhdl/vhdl-sem_psl.adb
testsuite/gna/issue1288/issue.vhdl
testsuite/gna/issue1288/testsuite.sh
testsuite/synth/issue1288/issue.vhdl
testsuite/synth/issue1288/testsuite.sh

This small PR fixes the handling of the PSL operator `next_e` as reported in bug #1288. I also added tests for simulation & synth. The CI seems to be happy, so have a look and please merge :)

Fix for PSL next_e operator

---

testsuite/gna/issue1295/psl_next_event_a.vhdl
testsuite/gna/issue1295/testsuite.sh
testsuite/synth/issue1292/issue.vhdl
testsuite/synth/issue1292/testsuite.sh
testsuite/synth/issue1295/issue.vhdl
testsuite/synth/issue1295/testsuite.sh

This PR adds tests for the PSL next_event_e & next_event_a operators. Both were recently fixed, see issue #1292. This closes issue #1295.
CI seems to be happy, so please merge :)

Add tests of synth/sim for #1292 and #1295

---

doc/internals/AST.rst
doc/internals/Frontend.rst

doc: fix typos in 'internals'

---

src/grt/grt-rtis.ads
src/grt/grt-rtis_addr.ads
src/grt/grt-rtis_utils.adb

This adds a bunch of comments to the RTI processing mostly in grt-rti.adb.
I'm using the term "instantiation data" to refer the data for an RTI node that is used for a particular context of that node.  Not sure if that's a good choice of name.

Adding some comments to the RTI processing.

---

.github/workflows/doc.yml
.github/workflows/push.yml
.gitignore
Makefile.in
dist/ci-run.sh
dist/msys2-mingw/llvm/PKGBUILD
dist/msys2-mingw/mcode/PKGBUILD
dist/msys2-mingw/run.sh

This PR includes multiple enhancements to how `version.tmp` is generated:
- <strike>Instead of being a make target, `version.tmp` is generated in `configure`</strike>.
- <strike>Instead of requiring `make` to override the version description</strike>, environment variable `GHDL_DESC` is supported <strike>by `configure`</strike>. The precedence is as follows:
- If this is a cloned repo and git exists, `git describe --dirty`.
- If `GHDL_DESC` is defined, use it.
- Default to `tarball`.
- The new environment variable is used in `dist/ci-run.sh` for customizing the description of the packages built in CI: `GHDL_DESC="$(git describe --dirty)@${BUILD_IMAGE_TAG}"`.
- Updating actions/checkout to v2 revealed that Windows build scripts have the same "unshallow" issue as Linux builds. It is fixed …

rework 'version.tmp'

---

src/grt/ghwlib.c
testsuite/gna/issue1326/mytestbench.vhdl
testsuite/gna/issue1326/testsuite.sh

This adds a test that checks that ghwdump doesn't crash on a signal of zero length.
The solution in the pull request just removes the offending assertion in ghwlib.c.
Presumably there is a good reason that this assertion was there, and a better solution is required.
The error message when the assertion is present is:
```
ghwdump: ../../../src/grt/ghwlib.c:1317: ghw_disp_hie: Assertion `sigs[0] != GHW_NO_SIG' failed.
```

ghwdump should handle zero-length signals

---

.github/workflows/doc.yml
.github/workflows/push.yml
.travis.yml
appveyor.yml

Close #1320
This is a proposal for providing "nightly" builds to be used in GitHub Actions workflows. Currently, docker images are provided, which can be used on Linux (`ubuntu-latest`). But, using latest GHDL on `windows-latest` or `macos-latest` requires users to build it themselves. At the same time, artifacts for all (Linux, Windows and macOS) are created in each run of the default workflow in this repo. The proposal is to keep these artifacts in a fixed location, so users can retrieve them easily. It is complemented with a GitHub Action, which can make setup easier.
---
- Currently, Debian docker images are used to test each of the backends on Linux. However, in ghdl/docker Ubuntu 18 images are available too. Since `ubuntu-latest` environment in GitHub Actions is Ubuntu 18, in this …

ci: use eine/tip to provide nightly releases

---

dist/ci-run.sh

This PR fixes the extraction of tag names on GitHub Actions workflows. The bug was shown when tag `nightly` was pushed some hours ago: https://github.com/ghdl/ghdl/actions/runs/110635016
The fact that building tag `nightly` fails is not relevant, because the tag itself is a placeholder only. Actual assets are produced and pushed from branch master. Still, it is good to have this fixed for future releases/tags.

ci: adjust pkg tag in ci-run.sh

---

dist/msys2-mingw/llvm/PKGBUILD
dist/msys2-mingw/mcode/PKGBUILD
doc/getting/Releases.rst
doc/helpers.py
doc/index.rst
doc/licenses.rst

Nightly pre-release and Action setup-ghdl-ci are announced in the docs. Section getting/Releases is updated accordingly, and `doc/helpers.py` is fixed to ignore `nightly` in the list of regular releases.

doc: announce nightly pre-release and Action setup-ghdl-ci

---

.github/workflows/push.yml

The most meaningful change in this PR is that update setup-msys2 from v0 to v1 reduces startup of Windows jobs from 10-12 min to 1-2 min (see https://github.com/eine/setup-msys2/issues/23#issuecomment-639837574).
Apart from that, `defaults` at job level are used to set the shell to `msys2`. This reduces verbosity slightly.

ci(msys2): update eine/setup-msys2 to v1, set default shell

---

src/synth/synth-expr.adb
src/vhdl/vhdl-prints.adb
src/vhdl/vhdl-sem_expr.adb
src/vhdl/vhdl-sem_psl.adb
src/vhdl/vhdl-sem_psl.ads
testsuite/synth/issue662/psl_prev.vhdl
testsuite/synth/issue662/psl_stable.vhdl
testsuite/synth/issue662/tb_psl_prev.vhdl
testsuite/synth/issue662/tb_psl_stable.vhdl
testsuite/synth/issue662/testsuite.sh

I want to add synthesis of PSL built-in `stable()` function. See #662 for the Issue which tracks support of PSL built-in functions in GHDL.
As I'm not an expert of the GHDL code base, I can't get it completely right. I've looked after the changes which were done for PSL `prev()` synthesis and tried to add similar changes for PSL `stable()`. However, the function which synthesizes the `stable()` function don't compiles. Honestly, I'm confused about the many types and sub types declared and when to use which one.
GNAT complains about this funtion in  `src/synth/synth-expr.adb`:
```ada
function Synth_Psl_Stable (Syn_Inst : Synth_Instance_Acc; Call : Node)
return Valtyp
is
Ctxt      : constant Context_Acc := Get_Build (Syn_Inst);
Clock     : Node;
Dff       : Net;
Clk       : …
```

WIP: Synthesis of PSL stable() function.

---

src/synth/synth-expr.adb
src/vhdl/vhdl-prints.adb
src/vhdl/vhdl-sem_expr.adb
src/vhdl/vhdl-sem_psl.adb
src/vhdl/vhdl-sem_psl.ads
testsuite/synth/issue662/psl_rose.vhdl
testsuite/synth/issue662/tb_psl_rose.vhdl
testsuite/synth/issue662/testsuite.sh

So, now I try to implement synthesis of the PSL built-in `rose()` function. The code compiles, but the behaviour of the test case I have (not yet checked-in) is strange. Looks like `rose()` only works correct when the signal is one cycle valid after the rising edge 😕 
When the signal is two or more cycles valid, that rose seems to be valid each of these cycles, which is strange ...
The property `rose(a) -> not prev(a) and a;`
works with a = `__-__-__-__`
but not with a = `__-__-__--_`
I'm sure that using the `Build_Posedge()` function is too naive. Furthermore the ghdl-yosys-plugin throws an error:
```
ERROR: wire not found for $posedge
```

WIP: Synthesis of PSL built-in rose() function.

---

src/synth/synth-expr.adb
src/vhdl/vhdl-prints.adb
src/vhdl/vhdl-sem_expr.adb
src/vhdl/vhdl-sem_psl.adb
src/vhdl/vhdl-sem_psl.ads
testsuite/synth/issue662/psl_fell.vhdl
testsuite/synth/issue662/tb_psl_fell.vhdl
testsuite/synth/issue662/testsuite.sh

Next one. Similar additions as for `rose()`. But this time I get an error when synthesizing my example which states that the declaration of fell cannot be found. Is there something left to add on the parser side?
```
$  ghdl --synth --std=08 psl_fell.vhdl -e psl_fell
psl_fell.vhdl:17:43:error: no declaration for "fell"
*std_standard*:1:1:error: type of expression must be boolean
psl_fell.vhdl:20:29:error: no declaration for "fell"
*std_standard*:1:1:error: type of expression must be boolean
psl_fell.vhdl:23:28:error: no declaration for "fell"
*std_standard*:1:1:error: type of expression must be boolean
```

WIP: Synthesis of PSL built-in fell() function.

---

src/vhdl/vhdl-sem_expr.adb
testsuite/synth/issue662/psl_fell.vhdl
testsuite/synth/issue662/psl_rose.vhdl
testsuite/synth/issue662/psl_stable.vhdl

Small fix:
I added prev() to list of allowed expressions in `Check_Is_Expression()` function in `src/vhdl/vhdl-sem_exp.adb`. Furthermore I adjusted the test cases which use `prev()`.

Add PSL prev() function to allowed expressions

---

.github/workflows/push.yml
dist/msys2-mingw/llvm/PKGBUILD
dist/msys2-mingw/mcode/PKGBUILD
dist/msys2-mingw/run.sh

With this PR dependencies of MSYS2 packages are defined in PKGBUILD files, instead of installing them in the `run.sh` script. Then, scripts are simplified.

ci(msys2): define deps in PKGBUILD, cleanup run.sh

---

src/grt/grt-vpi.adb

This PR implements some of the missing functionality in the `vpi_get_vlog_info` VPI method: the version returned by the function now follows the release version, and the function returns `1` indicating success. While functionality is still missing, argc = `0` and argv = `NULL` is valid, so returning failure is not necessary.
This leaves one last bit of missing functionality in this function: returning argc and argv to C. While I'd like to see this implemented, I'm not familiar enough with Ada to do so.
This PR partially fixes #1396.

Partially fix vpi_get_vlog_info

---

Makefile.in

After #1255 makefile targets `test` and `test.*` were added. However, those expect the build directory to be the same as the source directory. This PR adds `$(srcdir)` to fix the targets when that's not true.

makefile: fix 'test' when builddir != srcdir

---

python/vhdl_langserver/lsp.py
python/vhdl_langserver/symbols.py

Previously, the language server crashed on unhandled symbols with an exception. As ignoring unhandled symbols should be fine, logging this as an error to the logger results in a much better user experience.
This fixes #1410.

ghdl-ls: Fix exception crashing language server

---

doc/using/ImplementationOfVHDL.rst

Small addition to the documentation of PSL support. As mentioned in #1027 PSL vunits are only supported with VHDL-08 and synthesis. These PR adds that information to the doc.

doc: Update and fix PSL documentation (vunits, see #1027, PSL functions)

---

python/libghdl/__init__.py
python/vhdl_langserver/document.py
python/vhdl_langserver/lsp.py
python/vhdl_langserver/lsptools.py
python/vhdl_langserver/main.py
python/vhdl_langserver/references.py
python/vhdl_langserver/symbols.py
python/vhdl_langserver/workspace.py

Why?
1. Conform to PEP 8.
2. Easier to read.
3. Make tools, such as PyCharm, not complain.

py: adjust blank lines to PEP 8 for vhdl_langserver

---

python/setup.py

Currently, using directly setup.py (without pip) fails to include `ghdl-ls`, as `entry_point` is not available in distutils.

Replace distutils with setuptools for pyghdl and remove unused import

---

configure
doc/getting/LLVM.rst

We need this in Fedora, because we already have the LLVM 11 release candidates available in the distro.

update for LLVM 11

---

dist/termux.sh

Fix #1458
I cannot test it in a "clean" environment, but it works in my existing termux installation.
/cc @BenjaminRenz

termux: update gnat, install llvm and make explicitly

---

src/ghdldrv/ghdlcomp.adb
src/ghdldrv/ghdldrv.adb
src/ghdldrv/ghdllocal.adb
src/ghdldrv/ghdlmain.adb
src/ghdldrv/ghdlprint.adb
src/ghdldrv/ghdlrun.adb
src/ghdldrv/ghdlsynth.adb
src/ghdldrv/ghdlvpi.adb
src/ghdldrv/ghdlxml.adb
testsuite/testsuite.sh

This PR implements the initial proposal in #1204. Commands without `--` or `-` are supported, and others are defined as aliases. The help is modified accordingly.
I modified the testsuite for printing the help at the end. As a result, the proposed new layout can be seen in the tests below.
There are two sets of commands which are defined differently, and I didn't know how define aliases for them, so I left them untouched (the layout changed only). Those are `--libghdl-*` and `--vpi-*` commands, defined/registered in `ghdlvpi.adb` and `ghdlsynth.adb`, respectively.
Apart from that, there are some commands which have the same prefix. For example `disp-config` and `disp-std`, or `gen-makefile` and `gen-depends`. The last two are close, but `disp-*` are far from each other. I tried to …

Revisit CLI syntax

---

.github/workflows/doc.yml
doc/conf.py

Ref #484 #1437
In this PR browsable documentation of the codebase is generated with `gnatdoc` and published to the site. See https://umarcor.github.io/ghdl/gnatdoc/

doc: add gnatdoc HTML output

---

doc/using/ImplementationOfVHDL.rst

Small update to PSL documentation adding a hint that all directives has to be clocked. Not only `assert` as  before.

PSL doc: only clocked directives are supported

---

doc/using/Synthesis.rst

Adding documentation of synthesis specific options in the Synthesis document. I don't have checked how it looks in the RTD, as I don't remember how I could.

Synth doc: add infos about synth specific options

---

doc/getting/PrecompileVendorPrimitives.rst
libraries/vendors/compile-lattice.ps1
libraries/vendors/compile-lattice.sh

I added a MachXO3D FPGA option to the precompilation script, since this is the FPGA I am currently working on and it was simple enough to add. I also updated the docs indicating that it is supported.

vendor-libs: add machxo3d support

---

configure
dist/msys2-mingw/llvm/PKGBUILD
src/grt/Makefile.inc

Currently, building GHDL with LLVM backend using clang on MSYS2/mingw64 fails because the output of `clang -dumpmachine` is not supported.
On GNU/Linux:
```
x86_64-linux-gnu
x86_64-pc-linux-gnu
```
On MINGW64:
```
x86_64-w64-mingw32
x86_64-w64-windows-gnu
```
This PR fixes `configure` and `src/grt/Makefile.inc` for detecting `x86_64-w64-windows-gnu` properly. At the same time, the PKGBUILD recipe is modified to use `CC=clang` and `CXX=clang++`.
The build is successful and several tests do pass. However, one of the tests in gna fails:
```
gna issue635: failed
analyze tb.vhdl ram.vhdl fsm.vhdl
ram.vhdl:29:15:warning: declaration of "ram" hides entity "ram" [-Whide]
elaborate and simulate (failure expected) testbench
../../src/ieee2008/numeric_std-body.vhdl:3036:7:@100ns:(assertion warning): …
```

Support building GHDL with LLVM backend using clang on MSYS2/mingw64

---

src/vhdl/vhdl-sem_stmts.adb

"time must be **greather** than previous transaction" -> "time must be **greater** than previous transaction"
(h was in the word 'greater')
No issues fixed, just a typo.

vhdl-sem_stmts: fix typo

---

testsuite/gna/bug097/testsuite.sh
testsuite/gna/issue1226/testsuite.sh
testsuite/gna/issue1228/testsuite.sh
testsuite/gna/issue1233/testsuite.sh
testsuite/gna/issue1256/testsuite.sh
testsuite/gna/issue1326/testsuite.sh
testsuite/gna/issue450/testsuite.sh
testsuite/gna/issue531/testsuite.sh
testsuite/gna/issue98/testsuite.sh
testsuite/testenv.sh
testsuite/vpi/vpi001/testsuite.sh
testsuite/vpi/vpi002/testsuite.sh
testsuite/vpi/vpi003/testsuite.sh

**Background**
Related to ghdl/docker#34.
We want to have a docker image with ghdl that is minimal in size. That implies not including a gcc installation in the image. We do however want to run the testsuite to make sure the docker image "works".
This PR makes it possible to run the testsuite on a system that does not have gcc installed. Tests that require gcc will be skipped (reported as "ok").

Skip some tests if gcc is not installed

---

src/grt/config/win32.c

Honestly, I don't know how to explain this. Since MSYS2 recipes were modifidied for using clang when building with LLVM backend (#1497), one test has been failing in CI: issue635. It is difficult to debug, because I cannot reproduce locally.
The issue is that the exit code is `3`, when it should be `0`. I run the test on GDB in CI, and I could confirm that: https://github.com/eine/ghdl/runs/1422980823?check_suite_focus=true#step:8:64. Then, Tristan told me that the issue might be in `src/grt/config/win32.c`. Hence, I added some `printf` statements, to see which functions are used. Surprisingly, that fixed the issue. I removed the print statements one by one, until I came to this minimal "fix".
So, adding an empty printf statement to `grt_save_backtrace` fixes the issue, but I cannot …

win32: add fprintf to grt_save_backtrace

---

.gitignore
src/grt/config/chkstk.S

This PR adds an `.note.GNU-stack` section to `chkstk.o`, which fixes #1524.
Additionally, it updates `.gitignore` to ignore a few additional generated files on linux. I sorted the "generated files list" to be easier comparable.

Fix 'ghdl build produces an executable with RWX sections'

---

.github/workflows/push.yml
dist/msys2-llvm/PKGBUILD
dist/msys2-mcode/PKGBUILD

This PR updates the CI workflow in order to test MSYS2 packages in separated jobs, instead of doing it in the same job where the packages are built. The main motivation for doing so was reducing execution time. `vests` and `synth` test suites on Windows need ~15min each when LLVM backend is used. Executing suites in parallel should reduce overall time 5-10min.
While testing it, I found that pyunit tests require `gcc-ada` on MSYS2 shells. Otherwise, loading libghdl fails. Hence, I added the dependency to the PKGBUILD recipes.

ci/msys2: split build and test

---

.github/workflows/push.yml
scripts/update_py_bindings.sh

This PR adds an script for regenerating all python bindings in pyGHDL. At the same time, a test is aded to CI. It will produce a failure if a commit is pushed without updating pyGHDL sources (if required).

scripts: add 'update_py_bindings.sh'

---

doc/using/Synthesis.rst
src/ghdldrv/ghdlsynth.adb
src/synth/netlists-disp_vhdl.adb
src/synth/synth-flags.ads
src/synth/synth-stmts.adb
testsuite/synth/assertassumes0/assert0.vhdl
testsuite/synth/assertassumes0/testsuite.sh
testsuite/synth/assumeasserts0/assume0.vhdl
testsuite/synth/assumeasserts0/testsuite.sh

This adds the ability to GHDL synthesis to treat PSL assertions as PSL assumes and vice-versa.
It adds two new options to the `--synth` command:
Treat all PSL assertions as PSL assumes
Treat all PSL assumes as PSL assertions
The options names mimic their counter parts of the Yosys [`read_verilog`](http://www.clifford.at/yosys/cmd_read_verilog.html) command. If we want other names (`assert` instead of `asserts`  for example), I am happy to discuss this.
Furthermore the PSL implementation documentation is enhanced with these two options.
This is a work-in-process. Test cases will be added before the PR is finished.

synth: Add option to treat PSL asserts as PSL assumes and vice-versa

---

pyGHDL/libghdl/__init__.py
pyGHDL/libghdl/errorout_memory.py
pyGHDL/libghdl/files_map.py
pyGHDL/libghdl/files_map_editor.py
pyGHDL/libghdl/flags.py
pyGHDL/libghdl/libraries.py
pyGHDL/libghdl/name_table.py
pyGHDL/libghdl/utils/__init__.py
pyGHDL/libghdl/vhdl/__init__.py
pyGHDL/libghdl/vhdl/canon.py
pyGHDL/libghdl/vhdl/flists.py
pyGHDL/libghdl/vhdl/formatters.py
pyGHDL/libghdl/vhdl/ieee.py
pyGHDL/libghdl/vhdl/lists.py
pyGHDL/libghdl/vhdl/nodes_utils.py
pyGHDL/libghdl/vhdl/parse.py
pyGHDL/libghdl/vhdl/scanner.py
pyGHDL/libghdl/vhdl/sem.py
pyGHDL/libghdl/vhdl/sem_lib.py
pyGHDL/libghdl/vhdl/std_package.py

As we now know what files are auto generated, here are the remaining file headers incl. license info for Python files.
**Changes:**
* Add more missing file headers (incl. license info) to non-autogenerated Python files.
* Reordered import statements to:
1. Python standard library
2. Globally installed
3. Current project.
Hint: To avoid merge conflicts, some files already contain imports of `pydecor`. pydecor offers an `export` decorator to automatically list public classes and functions in the interface description `__all__`. This is later used by Sphinx to auto generate documentation.

Add missing file headers and reorder import statements

---

doc/ghdl.1

The manual page still contained a link to the free.fr-hosted, pretty dated GHDL documentation.
Replaced that with a link to the readthedocs page.
Not happening here.

manpage: updated Link to modern documentation

---

libraries/vendors/README.md
libraries/vendors/compile-uvvm.ps1
libraries/vendors/compile-uvvm.sh
libraries/vendors/shared.sh

**Changes:**
* Fixed `ccv` vs. `vvc` typo.
* Read `component_list.txt` also in Bash-based script.
* `--halt-on-error` to work for Bash-based script.
* Handle `\n` / `\r\n` problem.
It was tested with uvvm/uvvm@51f9287.
A problem was reported to UVVM as uvvm/uvvm#130.
Thanks to @tpcorrea.

Improvements to the UVVM pre-compile scripts.

---

testsuite/gna/testsuite.sh
testsuite/sanity/testsuite.sh
testsuite/suite_driver.sh
testsuite/synth/testsuite.sh
testsuite/testsuite.sh
testsuite/vpi/testsuite.sh

Close #723
`testsuite/gna/testsuite.sh`, `testsuite/sanity/testsuite.sh`, `testsuite/synth/testsuite.sh` and `testsuite/vpi/testsuite.sh` are almost identical. In this PR, `testsuite/suite_driver.sh` is created, which takes the target suite name as the first argument. Then, those four testsuites are rewritten for calling the suite_driver. At the same time `testsuite/testsuite.sh` is updated for calling the suite_driver directly. BTW, positional arguments to be passed to the suite_driver are supported:
```sh
./testsuite.sh
./testsuite.sh gna
./testsuite.sh gna -- -k
./testsuite.sh -- -k
```

testsuite: add suite_driver.sh

---

libraries/vendors/compile-uvvm.ps1
libraries/vendors/compile-uvvm.sh

This fixes:
* Removal of optional `\r` character in Windows checked-out Git environments.  
note: `\n` was removed by the while loop.
* Handle empty lines in PowerShell with `.Trim()`
* Set exit code on errors.

Fixed corner cases and error reporting for UVVM pre-compile scripts.

---

.github/workflows/Test.yml
scripts/ci-run.sh
scripts/macosx/install-ada.sh

As commented in [#848](https://github.com/ghdl/ghdl/issues/848#issuecomment-510205566), this PR removes `--disable-libghdl` from the Mac OS job in Travis.

ci: enable libghdl on macOS, add LLVM job

---

.gitignore

After running the testsuite, a bunch of generated files clutter up the `git status` output. Adding only a few lines of `.gitignore` hides them all.

Add gitignore files for testsuite

---

configure
doc/development/building/LLVM.rst

We need this in Fedora, because we already have the LLVM 11.1 release candidates available in the distro. A similar update for LLVM 12 will follow soon.

update for LLVM 11.1

---

scripts/ci-run.sh

This reverts commit 30ee7a32b64c94f1ac0c8e3b5068894b6ea8b556 (#601), cc @eine .
This workaround masks the return value of `make`, causing runs to appear to fail during install, even though build failed already. Since travis is no longer used for CI, it's probably no longer necessary anyway.

revert "log stderr of make to a file and use tail to show last 1000 lines"

---

doc/using/Simulation.rst
src/grt/grt-vpi.adb
testsuite/vpi/vpi005/mydesign.vhdl
testsuite/vpi/vpi005/testsuite.sh
testsuite/vpi/vpi005/vpi1.c
testsuite/vpi/vpi005/vpi2.c

Store library information for all `--vpi=` options and load each in the order they are passed in.
Library file names are stored in a simple singly-linked list.

VPI: support loading multiple libraries

---

scripts/vendors/compile-xilinx-ise.sh

Pull request #1653 reintroduced deprecated script params, but with a
typo in one of the vendor scripts.
This PR fixes that mistake.
Sorry for this mess!

scripts/vendors: fix typo in deprecated script param

---

scripts/vendors/shared.sh

ghdl invocation in scripts/vendors was missing the `workdir` argument, causing the output files to be in the wrong directory.
Tested with compile-xilinx-vivado.sh.

scripts/vendors: add missing workdir argument

---

doc/using/Simulation.rst

Added documentation for --psl-report-uncovered option.
Closes #1690
- [ x] DO make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [ x] DO make sure you are making a pull request against the **master branch** (left side). Also you should start *your branch* off *our master*.
- [ x] DO make sure that GHDL can be successfully built. See [Building GHDL](https://github.com/ghdl/ghdl#building-ghdl).
- [ x] CONSIDER adding a unit test if your PR resolves an issue.
- [ x] CONSIDER modifying the docs, if your contribution is relevant to any of the content.
- [ x] AVOID breaking the continuous integration build.
- [ x] AVOID breaking …

Psl warn uncovered

---

doc/using/Synthesis.rst

On the one hand, a subsection named "Assertions, PSL and formal verification" is added to synthesis options.
On the other hand, synthesis option `--out` is documented. However, I'm not sure about the description of `raw` and `dump`. I'll keep this as a draft until it's clarified.

doc/using: document synth option '--out'

---

src/vhdl/vhdl-parse.adb

Provide better error messages for invalid location of variable declaration.

src: More detailed message on invalid variable locations.

---

src/vhdl/vhdl-parse.adb

Report missing parenthesis only once. If multiple are missing, then report also total count.
Keep flag of published report and reset once all parenthesis are popped.

src: Better reporting of missing parenthesis.

---

src/vhdl/vhdl-parse.adb

This PR unifies Parse error format for features unsupported before VHDL 2008.
Further, it allows case generate only for VHDL 2008, since it is not in LRM of previous versions.

Vhdl 2008 case generate

---

scripts/vendors/compile-altera.ps1
scripts/vendors/compile-intel.ps1
scripts/vendors/compile-lattice.ps1
scripts/vendors/compile-osvvm.ps1
scripts/vendors/compile-uvvm.ps1
scripts/vendors/compile-xilinx-ise.ps1
scripts/vendors/compile-xilinx-vivado.ps1
scripts/vendors/shared.psm1

Compilation of Xilinx Vivado 2019.2 vendor libraries on Windows fails with current version of the PS scripts. This PR includes all changes I needed to make to the compile-xilinx-vivado.ps1 script to run on my machine with ghdl-1.0.0. For release 0.37 compilation is successful without swapping --std=08 and -frelaxed-rules.
I have no build environment for GHDL under Windows, so it would be great if someone else could have a closer look to the changes to make sure they are complete and don't break anything.

Fix xilinx vendorlib compilation

---

src/grt/grt-avls.adb
src/grt/grt-signals.adb
src/grt/grt-signals.ads
src/grt/grt-types.ads
src/grt/grt-waves.adb

This PR pretty much duplicates [Wave-dump-optimize](https://github.com/ghdl/ghdl/pull/782), but it uses GRT sort
instead of Ada library sort for Wave table.
Branch was built with LLVM backend, and briefly tested (dumped waves seem to be the same as in GCC build before
the sort function modification)

Grt optimize wave dump

---

src/ortho/llvm6/llvm-cbindings.cpp

GHDL seems to be using a deprecated class DebugLoc. Switched to the suggested alternative. Now compiles fine for LLVM 12.

Migrate deprecated DebugLoc::get to DILocation::get

---

configure
src/ortho/llvm6/llvm-cbindings.cpp

I tested the earlier DILocation patch in original ghdl master. In order to submit it, I forked ghdl and applied the patch there. However I forgot to specify --with-lvm-config in configure (which was still effective in the original ghdl master). I now added the necessary check to pass.

Add missing llvm version check in configure

---

Makefile.in
testsuite/testsuite.sh

#1738 broke PKGBUILDs because tests are performed before GHDL is installed, so the `ghwdump` binary in the build directory must be used, however the `test` make targets don't set the `$GHWDUMP` variable.

Makefile.in: pass ghwdump location to testsuite

---

scripts/msys2-mcode/PKGBUILD

This fixes the stack overflow error when using UVVM axistream_vvc for msys2-mcode.

Increase stack size for msys2-mcode binary (fix #1742)

---

doc/ghw/index.rst
doc/using/Simulation.rst

See #1759.
This is just some cleanup/update of the documentation regarding waveforms.
- Add a note about GTKWave, instead of repeating it for each format.
- Remove the comments about filtering of signals not being supported.
- Add a reference to section GHW, instead of repeating the information.

doc/using: update wave filtering, add note about GTKWave, link to section GHW

---

pyGHDL/cli/DOM.py

This is a minor update to the DOM cli example, which allows passing the files to be analysed through CLI arguments, instead of hardcoding it. As a result, this script can be used for testing how are the VHDL sources in this repo supported by the VHDLModel implementation:
```sh
· ./doc/quick_start/simulation/adder/adder.vhdl
raised SYSTEM.ASSERTIONS.ASSERT_FAILURE : vhdl-nodes.adb:861
· ./testsuite/gna/bug084/func_test3.vhdl
Unknown declared item kind 'Type_Declaration'(91) in architecture 'fum'.
· ./testsuite/gna/bug084/mod5.vhdl
Unknown declared item kind 'Type_Declaration'(91) in architecture 'foo'.
· ./testsuite/gna/bug084/mod5x.vhdl
raised SYSTEM.ASSERTIONS.ASSERT_FAILURE : vhdl-nodes.adb:861
· ./testsuite/gna/issue652/ent.vhdl
raised SYSTEM.ASSERTIONS.ASSERT_FAILURE : …
```

pyGHDL/cli/DOM: support passing target files as CLI arguments

---

pyGHDL/libghdl/_decorator.py
pyGHDL/libghdl/_types.py
pyGHDL/libghdl/vhdl/nodes.py
pyGHDL/lsp/document.py
pyGHDL/lsp/workspace.py
scripts/pnodespy.py
src/vhdl/vhdl-nodes.ads

@Paebbels: here is my patch to add type annotations to nodes.py
I have tested it quickly on my computer, and I am using CI to check it more thoroughly.
I am pretty sure black will cry.
We need to settle on the type name convention.  We often strip `_` from Ada type names (like `Iir_Kind` -> `IirKind`), but not always (like `Location_Type`).  I think we should always strip the `_`.
There is still one mismatch: `Token_Type` is `Tok` in python, so that the literals are directly translated: `Tok_String` becomes `Tok.String`
I think this is my first self pull-request!

pyGHDL: add types to nodes py

---

pyGHDL/dom/InterfaceItem.py
pyGHDL/dom/Literal.py
pyGHDL/dom/formatting/prettyprint.py
testsuite/pyunit/SimpleEntity.vhdl

* Adds handling of initial values / default expressions.
* Adds 50% handling of floating point.
@tgingold  This PR is against your branch to add FP handling, so you can test it further.
Please have a look at `pyGHDL/dom/Literal.py` in the `FloatingPointLiteral`.
I think the handling of `Get_Fp_Value` needs change.
For testing, run `DOM.py`. It uses `SimpleEntity.vhdl` as a testcase.
```vhdl
library ieee;
use     ieee.std_logic_1164.all;
use     ieee.numeric_std.all;
entity entity_1 is
generic (
FREQ : real     := 100.0;
BITS : positive := 8
);
port (
Clock: in  std_logic;
Reset: in  std_logic := '0';
Q:     out std_logic_vector(BITS - 1 downto 0)
);
end entity entity_1;
...
```
Expected output:
```
Document 'testsuite\pyunit\SimpleEntity.vhdl':
Entities:
- entity_1 …
```

Added handling of Floating Point.

---

pyGHDL/cli/DOM.py
pyGHDL/dom/Aggregates.py
pyGHDL/dom/DesignUnit.py
pyGHDL/dom/Expression.py
pyGHDL/dom/Literal.py
pyGHDL/dom/Misc.py
pyGHDL/dom/Symbol.py
pyGHDL/dom/_Translate.py
pyGHDL/dom/formatting/prettyprint.py
pyGHDL/libghdl/_decorator.py
pyGHDL/libghdl/_types.py
pyGHDL/libghdl/errorout.py
pyGHDL/libghdl/std_names.py
pyGHDL/libghdl/vhdl/elocations.py
pyGHDL/libghdl/vhdl/nodes.py
pyGHDL/libghdl/vhdl/nodes_meta.py
pyGHDL/libghdl/vhdl/tokens.py
pyGHDL/requirements.txt
scripts/pnodespy.py
testsuite/pyunit/Current.vhdl
testsuite/pyunit/SimpleEntity.vhdl
testsuite/pyunit/dom/Expressions.py
testsuite/pyunit/dom/Literals.py

* Added new types (c_int64, c_double) to the decorator.
* Fixed typo `Iir_Kind` &rarr; `IirKind` in `pnodes.py`
* If a return type is an enum derived from `IntEnum`, it is automatically converted from `c_int32/int` to the enum.  
As to functions are used in the decorator, there is no `if...then...else` runtime overhead.
* Add decorator usage everywhere in auto generated API.
* Changed all TypeVars to use more specific CDLL types.
----------------
**TODOs:**
&rArr; **new PR**
&rArr; **new PR**
&rArr; **done**
I used `IirKind`. Is this correct?

Python-C/Ada Bindings - Updated decorator

---

pyGHDL/cli/DOM.py
setup.py

Similarly to `ghdl-ls`, this PR adds a `ghdl-dom` entrypoint when pyGHDL is installed, so that user can analise their sources directly:
```sh
$ ghdl-dom path/to/a/file
$ ghdl-dom path/to/a/file path/to/anothe/file ...
```
For instance:
```sh
Unknown expression kind 'String_Literal8'(11) in expression '1294'.
Unknown expression kind 'Aggregate'(185) in expression '1298'.
```

pyGHDL: add ghdl-dom entrypoint

---

pyGHDL/libghdl/__init__.py
testsuite/pyunit/dom/Sanity.py

**Problem Description**
If GHDL is installed standalone outside of MinGW (tested with MSYS2/MinGW64), all DLL dependencies are resolved correctly. This is independent of GHDL / libghdl being build with mcode or llvm backend.
However, if GHDL / libghdl and it's dependencies are not copied outside of MSYS2 (e.g. `C:\msys64\mingw64\...` to `C:\Tools\GHDL`), then Pythons ctypes.CDLL has problems in finding all dependencies. This is due to the fact that `%PATH%` is not correctly used to search for dependencies.
**Solution**
With CPython 3.8, a new API (`os.add_dll_directory`) was added to add a DLL search path. This is only necessary on Windows platforms, because the problem does not exist on Linux and more over Linux would offer a `LD_LIBRARY_PATH` variable to support shared library searches. …

Added DLL search path for Python ≥3.8.

---

.github/workflows/Test.yml
pyGHDL/cli/lsp.py
scripts/msys2-mcode/GetStandaloneDeps.sh
setup.py
testsuite/pyunit/lsp/LanguageServer.py

This PR enables the mcode build on MINGW64. Although code generation is not supported, features other than simulation do work.
Moreover, a job is added after testing on Windows, for generating "standalone" zipfiles for mcode32 and mcode64. Precisely, the MSYS2 packages are extracted and a shell script contributed by @Paebbels is used for adding DLLs.

ci: generate standalone zipfiles and add CPython jobs

---

ghw/libghw.c
testsuite/gna/issue418/golden_tc749.txt

When printing the type section, physical types do not have a trailing semicolon. This causes problems when comparing the golden outputs in the testsuite with my [Rust libghw/ghwdump reimplementation](https://gitlab.com/xiretza/ghw-rs), which always prints a trailing semicolon for any type table entry. While the rest of the expected output is not completely valid VHDL either, this just looks like an oversight.

libghw: add missing semicolon to physical type formatting

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/workflows/Test.yml
scripts/ci-run.sh

Since Debian Bullseye was released, ghdl/docker was updated accordingly. This PR changes the usage of Buster images to Bullseye.

Debian Bullseye was released

---

ghw/libghw.h

C++ compilers mangle the names in the libghw header. This prevents that from happening so they can properly be linked to a C++ application.

add cpp header check for libghw

---

pyGHDL/dom/_Utils.py
pyGHDL/libghdl/vhdl/utils.py

This adds a new binding for `vhdl-utils.Get_Source_Identifier` and uses this function in `pyGHDL.DOM`, so identifiers keep there casing.

Added binding to new function 'Get_Source_Identifier'.

---

src/ghdldrv/ghdlrun.adb
src/grt/grt-std_logic_1164.adb
src/grt/grt-std_logic_1164.ads
src/vhdl/translate/trans-chap7.adb
src/vhdl/translate/trans_decls.ads
src/vhdl/translate/translation.adb

Instead of swapping L/R arguments to try to create `?>=` and `?>`,
create a function for each which performs the not operation of `?<`
and `?<=` as defined by the LRM.
This causes the match_operators test from #1873 to pass.

Add explicit ?>= and ?> functions for translation.

---

scripts/vendors/compile-altera.ps1
scripts/vendors/compile-intel.ps1
scripts/vendors/compile-lattice.ps1
scripts/vendors/compile-uvvm.ps1
scripts/vendors/compile-xilinx-ise.ps1
scripts/vendors/compile-xilinx-vivado.ps1
scripts/vendors/shared.psm1

This fixes the vendor scripts written in PowerShell for a bug concerning `bool` vs. `switch` parameters.
Fixes #1766, fixes #1767.
-----------------
The problem is described here: [How to pass a switch parameter to another PowerShell script?](https://stackoverflow.com/questions/38009106/how-to-pass-a-switch-parameter-to-another-powershell-script)

Fixed PoSh scripting

---

.github/workflows/Test.yml

As commented in https://github.com/ghdl/ghdl/issues/1115#issuecomment-772951318, currently macos-11.0 is in "private preview" mode. We'll keep this as a draft until we can have it tested.

ci: run macOS 10.15 and 11.0

---

testsuite/gna/issue1872/match_operators.vhdl
testsuite/gna/issue1872/testsuite.sh

Add an exhaustive test for the matching operators.
Added a test for the matching operators that were recently added.
Note that currently this test fails, but I am not sure where in the code the incorrect value is coming from.
The tables failing are `?>` and `?>=` with the either L or R being `'-'`.
Here is the entire [output](https://github.com/ghdl/ghdl/files/7211615/output.txt) of the test, when run with severity `error` instead of `failure`.

Add test for matching operators.

---

Makefile.in
doc/ghdl.1

The Debian packaging uses a few patches against upstream to make packages build correctly and according to policy. A bunch of these are not Debian specific and should have been upstreamed a while ago, and here they are now. These are just a few lines of changes mainly in the Makefile.in.
The CURDIR change actually fixed a build failure under certain conditions, but I forgot under which conditions that happened and could not reproduce it anymore. Anyway, making sure not to use the PWD from the environment variables is probably a good idea since its value in the environment is not really dependable.

Upstreaming patches from Debian packaging

---

.editorconfig

Update .editorconfig with settings for Ada files.
Indent style and indent size values are the one that are currently used by the GHDL project.
(This PR aims to prevent editor with .editorconfig plugin to force the default tab indentation)

Update .editorconfig with settings for Ada files

---

src/synth/elab-vhdl_insts.adb

86fd1ab3 introduced a regression opening files in a different directory to the toplevel (log below).
I'm running with ghdl-yosys-plugin. I have modified ghdl's testsuite synth issue1190 to have the toplevel in a separate directory, it reproduces running as a ghdl-yosys-plugin test. It won't reproduce as part of ghdl's own testsuite, I'm not sure what the difference is. 
https://github.com/mkj/ghdl-yosys-plugin/tree/matt/relative-test/testsuite/issues/relative-file
```
env YOSYS=$HOME/inst/oss-cad-suite-20211201/bin/yosys ./testsuite.sh
INFO: not in CI
Synthesize  hdl/top.vhdl hdl/subdir/ram.vhdl -e
· /home/matt/inst/oss-cad-suite-20211201/bin/yosys -q -p ghdl  hdl/top.vhdl hdl/subdir/ram.vhdl -e
note: top entity is "top"
hdl/subdir/ram.vhdl:22:18:error: cannot open file: data/memory.dat …
```

Fix opening files relative to the current vhdl

---

pyGHDL/cli/dom.py

Black was updated to version 22, now CI is failing because it has some new opinions on formatting.

pyGHDL: reformat after update to black version 22

---

.editorconfig

VHDL supports only latin1/ISO 8859-1 as input encoding, but the editorconfig sets the charset to utf8 for all files. Override this only for VHDL sources.

editorconfig: set charset=latin1 for VHDL sources

---

scripts/vendors/compile-altera.ps1
scripts/vendors/compile-intel.ps1
scripts/vendors/compile-lattice.ps1
scripts/vendors/compile-xilinx-ise.ps1
scripts/vendors/compile-xilinx-vivado.ps1

**Description** Fix a bug where compiling vendor libraries on Windows using PowerShell fails when a system environment 
variable for the root path of the vendor tool is set. 
Close #1973 
This is my first pull request. I really don't now how to check everything on the list, in particular how to start a build or run the tests using the CI.

Fix getting vendor tool directory from environment variable using PowerShell

---

README.md
doc/about.rst
doc/using/ImplementationOfVHDL.rst
src/flags.adb
src/flags.ads
src/ghdldrv/ghdllocal.adb
src/libraries.adb
src/options.adb
src/vhdl/vhdl-sem_assocs.adb
src/vhdl/vhdl-std_package.adb

This simply adds the command line option and updates the documentation. There is not yet any difference in simulator behaviour between `--std=08` and `--std=19`. Furher, since no 2019 standard library has been added yet, `--std=19` can't actually be used outside of bootstrapping.

Add --std=19 command line option

---

src/vhdl/vhdl-sem_types.adb

This implements [LCS-2016-014a](http://www.eda-twiki.org/cgi-bin/view.cgi/P1076/LCS2016_014a). It is required for the VHDL-2019 standard library to analyze.

vhdl-sem_types: allow file and protected type access types in VHDL-2019

---

src/vhdl/vhdl-sem_types.adb

This implements [LCS2016_004](http://www.eda-twiki.org/cgi-bin/view.cgi/P1076/LCS2016_004). It is required for the VHDL-2019 standard library to analyze.

vhdl-sem_types: allow methods to return file and protected types in VHDL-2019

---

src/vhdl/vhdl-sem_decls.adb

This implements [LCS-2016-002](http://www.eda-twiki.org/cgi-bin/view.cgi/P1076/LCS2016_002), at least in the analyzer. This is required in order for the VHDL-2019 standard libraries to analyze.

vhdl-sem_decls: allow out/inout parameters to impure function in VHDL-2019

---

Makefile.in
configure
scripts/gcc/Make-lang.in
src/ghdldrv/default_paths.ads.in
src/ghdldrv/ghdldrv.adb
src/ghdldrv/ghdllocal.adb
src/ghdldrv/ghdlsynth.adb
src/ghdldrv/ghdlvpi.adb
src/grt/Makefile.inc

66cd5e0aa897b947533d269535fde4c0852472c2 seems to have introduced breakage in `--libghdl-include-dir` and while I'm at it I'm also proposing a patch from the ghdl Debian package to fix this sort of thing once and for all by introducing new ./configure variables for the inc/libdirsuffix.

Fix --libghdl-include-dir ghdl/ suffix, etc

---

Makefile.in

This fixes some test errors when running `make test` right after a build.
See #1997

mk: Add test target dependency on install.vpi.local

---

scripts/vendors/compile-lattice.sh

The Lattice Diamond variable in config.sh is called `Lattice_Diamond_Settings`. `LatticeDiamond` was an incorrect prefix which never matched the settings, so they were never used.

Fix name of Lattice Diamond settings variable

---

src/ghdldrv/ghdldrv.adb
src/ortho/mcode/ortho_code-x86-abi.adb
src/synth/netlists-disp_dot.ads
src/synth/netlists-inference.ads
src/synth/synth-vhdl_stmts.adb
src/vhdl/translate/trans-chap2.adb
src/vhdl/translate/trans-rtis.adb

GCC 12 introduced a couple new diagnostics, which are causing compile failures due to -Wall. One of those was already reported in #2056, but there were a couple more, which are fixed here.

GCC 12 compatibility

---

src/options.adb

This adds a -Wall flag, in order to enable all warnings at once.
I succesfully built with llvm. I have not attempted to use another compiler.
Not relevant.
Relevant, but I do not yet know how to do this.

Add the -Wall flag.

---

configure

**Description** Use the `--version` option over `-v` to check for existing compilers
`-v` does not only print the compiler version, but runs some commands according to `gcc --help` and `clang --help`. This has side effects, which breaks things on some setups. I also think that's what was originally intended.

use --version flag to check for C compiler

---

src/grt/config/jumps.c

HAVE_BACKTRACE is now only defined as 1 on Linux systems if glibc is present, This is done by checking if the `__GLIBC__`
macro is defined, which it will be if glibc is on the system. This allows for successful building on non glibc systems (for example musl) which do not define a `backtrace()` function.
Tested build on Void Linux w/ musl & Ubuntu Linux w/ glibc

Support non glibc Linux systems

---

src/synth/netlists-disp_verilog.adb

When using `ghdl --synth --out=verilog` on Microwatt, I get a lot of verilator warnings of the sort:
```
%Warning-INITIALDLY: microwatt.v:112548:16: Delayed assignments (<=) in initial or final block
: ... Suggest blocking assignments (=)
112548 |     ext_rst1_n <= 1'b0;
|                ^~
```
The following patch fixes the warnings. I tried to find every assignment within an `always @*` process as well as any `initial` statements.

netlists-disp_verilog: Use blocking assignments in non-clocked blocks

---

doc/requirements.txt
pyGHDL/cli/dom.py
pyGHDL/cli/requirements.txt
pyGHDL/dom/NonStandard.py
pyGHDL/dom/_Translate.py
pyGHDL/dom/requirements.txt
pyGHDL/libghdl/requirements.txt
pyproject.toml
testsuite/pyunit/dom/Sanity.py

* Enabled `--ams` on all analysis runs with pyGHDL.
* This solves problems with `sanity/004all08/ams08.vhdl` due to not enabled VHDL-AMS support.
* Bumped dependencies
* Sphinx 5.0.x
* pyTooling 2.1.x
* Added more `[NOT IMPLEMENTED]` printouts for (yet) unsupported VHDL-AMS language constructs.
* Changed execution of sanity checks to run in same process, but not as external instance with `subprocess.call`.

Bumped dependencies to support pyTooling ≥2.0.

---

scripts/vendors/README.md

The [readme](https://github.com/ghdl/ghdl/blob/79e241b79eef8c6364038cbc3608e792f31e6124/scripts/vendors/README.md) for using the precompile vendor scripts contains outdated links to the docs. This PR fixes the links to
<http://ghdl.github.io/ghdl/getting.html#precompile-vendor-primitives> (and fixes a tiny typo).

Fix outdated link in precompile vendor readme

---

src/grt/vhpi_user.h

Nested comments produce  a warning when compiling, remove them. Also fixes trailing whitespace in this file.

Fix nested comments

---

scripts/vendors/compile-altera.ps1
scripts/vendors/compile-intel.ps1
scripts/vendors/compile-lattice.ps1
scripts/vendors/compile-osvvm.ps1
scripts/vendors/compile-uvvm.ps1
scripts/vendors/compile-xilinx-ise.ps1
scripts/vendors/compile-xilinx-vivado.ps1
scripts/vendors/shared.psm1

**Update**
As discussed [here](https://github.com/ghdl/ghdl/pull/2108#discussion_r906032565) and [here](https://github.com/ghdl/ghdl/issues/2107#issuecomment-1165541878) I changed the PR to only fix the docstring in the preocompile scripts and a small bug in `shared.psm1`.
- 290b4d41ba91ee4fb4af91ba8d92108ea8f391ce fixes the try/catch when calling `Get-Command`. Before, the catch condition
is never met what leads to this error message, when `ghdl..exe` is not on PATH:
```
Get-Command: The term 'ghdl.exe' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
Test-Path: Value cannot be null. (Parameter 'The provided Path argument was null …
```

Fix docstring and a small bug in PoSh precompile script

---

testsuite/gna/issue394/testsuite.sh
testsuite/gna/issue450/testsuite.sh
testsuite/gna/issue719/testsuite.sh
testsuite/gna/issue880/testsuite.sh
testsuite/gna/ticket24/testsuite.sh

I just had a [spurious test failure](https://github.com/Xiretza/ghdl/runs/6456572177?check_suite_focus=true#step:7:798) in one of my branches (`gna/issue880` failed only in MINGW64 llvm), but unfortunately the only message was "report mismatch" because the output of the `diff` was swallowed. Replacing all occurrences of `diff.*-q` and `diff.*/dev/null` should make future test failures more debuggable.

fix(testsuite): show diffs on comparison failure

---

src/synth/synth-vhdl_oper.adb
testsuite/synth/issue2126/test.vhdl
testsuite/synth/issue2126/testsuite.sh

Fixes issue #2126, adds handling of the to_ux01 function to synthesis

Fix issue #2126, add handling of to_ux01 to synthesis

---

src/synth/synth-vhdl_expr.adb

**Description** Adds iir_kind_selected_element to Synth_Expression. This fixes a crash in the codebase I am working on. Even after bisecting through the codebase by commenting out code, I'm still not sure what the problematic lines are so I'm unable to make a testcase for this. 

Fix access check failed from iir_kind_selected_element

---

src/psl/psl-prints.adb

I'm trying to read in & understand GHDLs processing of PSL constructs a little bit better. So I found out that one can print the resulting NFAs on the console in a Grapvhiz-compatible format - very nice feature 🙂.
During experimenting with that on some PSL examples I stumbled over the error, that `N_HDL_Bool` type can't be printed, resulting in a GHDL error:
```
$ ghdl -a --std=08 issue_2153.vhd
NFA to determinize:
digraph nfa {
rankdir=LR;
node [shape = circle, style = bold]; /* Start: */ 0;
node [shape = doublecircle, style = solid]; /* Final: */ 1;
node [shape = circle, style = solid];
0 -> 1 [ label = "HDL_Expr" /* Node = 10 */ /* Edge = 4 */ ];
0 -> 0 [ label = "!HDL_Expr && !HDL_Expr" /* Node = 26 */ /* Edge = 5 */ ];
}
Result state 0 for 0
Result state 1 for
Handle result state 0 …
```

PSL: Add handling of N_HDL_Bool to Dump_Expr procedure

---

doc/using/InvokingGHDL.rst

Document how -frelaxed treats conformance rules for subprograms after #2165 
**Note**
I have not performed the below activity because I do not know how to build the docs.
```
```

Document changes to -frelaxed from #2165

---

README.md

That page has been moved, and the old URL now results in a 404 error.

doc: update URL to IEEE 1076 standard

---

pyGHDL/libghdl/vhdl/scanner.py

Added return type annotations to the functions `Get_Token_Position` and `Get_Position` in `scanner.py` to fix #2192

pyGHDL: added missing type annotations. Fix #2192

---

src/grt/grt-options.adb

The `-g` run option to override a generic in the top-level entity is documented here:
https://ghdl.github.io/ghdl/using/Simulation.html
But it is not included in the CLI help for run options listed by `ghdl run-help` (i.e. the `RUNOPTS` when running `ghdl help -r`).
This PR simply adds `-g` to `ghdl run-help` under the "Additional features" category (I'm not sure where it would best fit in). Output with the change below:
```
$ ghdl run-help
These options can only be placed at [RUNOPTS]
Options are:
--help, -h        disp this help
--assert-level=LEVEL   stop simulation if assert at LEVEL
LEVEL is note,warning,error,failure,none
--backtrace-severity=LEVEL  display a backtrace for assertions
--ieee-asserts=POLICY  enable or disable asserts from IEEE
POLICY is enable, …
```

Add missing -g for generic override to CLI help for RUNOPTS

---

src/synth/netlists-disp_dot.adb

This escapes port names in dot output to prevent any signal name starting with the character 'r' from being escaped.
Example : "\rstn" -> "CR stn"
This will also prevent \n and \t from being escaped.
This does not fix an issue.

Escape port name in dot output.

---

.github/dependabot.yml
.github/workflows/Test.yml
pyGHDL/libghdl/errorout.py
pyGHDL/libghdl/file_comments.py

This PR updates used GitHub Actions in the workflow. It should reduced the number of warnings issued by GHA about node.js 12.
It also enables dependabot for dependency scanning and creating PRs with dependency updates (if PR gets accepted).

Updaing used GitHub Actions

---

src/synth/netlists-inference.adb

Do not merge this ! This is not a real pull request.
I was wondering why yosys was freaking out on any hdl with latches in it when I saw this.
Mostly I am wondering why this is here. I applied the patch locally and tried synthesising a few designs with latches.
So far, it seems to work all right.
Is there a reason this is disabled that I am not seeing ?

Restore latch inference.

---

pyGHDL/__init__.py
pyGHDL/dom/NonStandard.py
pyGHDL/dom/_Utils.py
pyGHDL/dom/__init__.py
pyGHDL/libghdl/__init__.py
pyGHDL/libghdl/flags.py
pyGHDL/libghdl/libraries.py
pyGHDL/libghdl/vhdl/nodes.py
pyGHDL/libghdl/vhdl/std_package.py
scripts/pnodespy.py
testsuite/pyunit/dom/Sanity.py
testsuite/pyunit/dom/VHDLLibraries.py

* Added new flags:
* `MB_Comment`
* `Explicit`
* `Relaxed`
* `AMS_Vhdl`
* Activate VHDL-2008 if selected VHDL dialect is VHDL-2008.
* Activate VHDL-AMS if selected VHDL dialect is VHDL-AMS.
* Added parsing of VHDL libraries to the pyGHDL tests:
* ieee2008
* mentor
* synopsys
* vital2000
* ReST improvements in the documentation.
* Documented `CheckForErrors` and other helper functions.
* Improved exception handling in `GetModeOfNode`.
*None*

Activate VHDL-2008 and VHDL-AMS based on selected VHDL dialect

---

src/synth/synth-vhdl_oper.adb
testsuite/synth/issue2286/tb_test_addsub.vhdl
testsuite/synth/issue2286/test_addsub.vhdl
testsuite/synth/issue2286/testsuite.sh

This should fix #2286 by adding the missing functions in `Synth_Dynamic_Predefined_Call` function of `synth-vhdl_oper.adb`.
A simple test is included.

synth: add support for numeric_std_unsigned add, sub, fix #2286

---

doc/requirements.txt

This should delay the problem with Sphinx until the RTD theme is fixed with respect to docutils 0.18/0.19.

Limit Sphinx to 5.3 <= XX < 6.0

---

src/synth/netlists-disp_dot.adb

This fixes the output ports being absent from the dot output of synthesis, and removes the dummy instance that was present.
There is no relevant issue.

Dot output ports

---

Makefile.in

Add makefile recipes to add dll dependencies in the install directory.
Could be used to build standalone windows package.

Windows dlldeps

---

doc/conf.py
doc/requirements.txt

In #2283, the docs conf file was changed to use upstream `sphinx.ext.inheritance_diagram` and `sphinx.ext.graphviz`. However, the requirements file was not updated accordingly. This PR removes `btd.sphinx.graphviz` and `btd.sphinx.inheritance_diagram` from `docs/requirements.txt`.

doc: update requirements

---

.github/workflows/Test.yml

In https://github.com/ghdl/ghdl/commit/ed54e7f29fcadd7c443a5cf708b0723a82fa27aa, UCRT64 LLVM was disabled. That was/is provided through ghdl-setup-ci, and it's used by projects such as OSVVM (see https://github.com/OSVVM/OsvvmLibraries/blob/main/.github/workflows/Test.yml#L67). Those are now failing: https://github.com/OSVVM/OsvvmLibraries/actions/runs/4294470208.
This PR enables UCRT64 LLVM builds and tests. It also enables MINGW64 LLVM tests.
Alternatively, we can stop supporting UCRT64 and suggest users to consume MINGW64 LLVM only. Yet, I think that MSYS2 is making UCRT64 the default...
/cc @JimLewis

ci: enable UCRT64 LLVM and test MINGW64 LLVM

---

doc/conf.py
doc/index.rst
doc/requirements.txt

This PR adds html_theme_options to:
- Have an "edit" button shown at the top.
- Show the `release` only below the logo in the sidebar.
- Have a "github" button at the bottom pointing to the repo.
As an alternative to showing the release below the logo, we could show no text (just the logo). See https://pradyunsg.me/furo/customisation/#sidebar-hide-name. What do you prefer?
This PR includes some other minor issues:
- Fixing the indentation of some list in the index.
- Reversing the date format of the headings in the index so that the year is shown first.
- Cleaning unused dependencies/extensions.
Ref #2364

doc/conf: add html_theme_options

---

NEWS.md

The NEWS file (https://github.com/ghdl/ghdl/blob/master/NEWS.md) is a markdown source. However, headings are not used.
GitHub and GitLab do automatically generate a ToC for markdown sources. This PR adds headings to `NEWS.md`, so that the automatically generated ToCs can be used for more easily navigating the document. See https://github.com/umarcor/ghdl/blob/umarcor/news-headings/NEWS.md and:

news: add headings

---

NEWS.md

I created a new milestone for ![GitHub milestone](https://img.shields.io/github/milestones/progress/ghdl/ghdl/12?style=flat-square) and changed all the open issues assigned to ![GitHub milestone](https://img.shields.io/github/milestones/progress/ghdl/ghdl/11?style=flat-square).
This PR updates the NEWS file to add a reference to the new milestone. At the same time, shields/badges are used to show the number of issues for each milestone. Moreover, the changes listed in "pre-release" tags are moved to their corresponding "release" tag, for consistency in the news file.

NEWS: update

---

pyGHDL/cli/requirements.txt
pyGHDL/libghdl/requirements.txt
pyproject.toml

In preparation for a breaking change in pyTooling, the version will be limited to >=2.13, but <3.0.
In `pyTooling` 3.0, `pyTooling.TerminalUI` will be integrated instead of a standalone project. There will be at the beginning no API change, but the two packages will overlap in installation directories.
------------
When pyTooling 3.0 is released, the dependency structure in GHDL can be simplified.

Limiting versions of pyTooling to >=2.13, but <3.0.

---

pyGHDL/dom/Sequential.py
pyGHDL/dom/_Translate.py

There was no handling for exit statements. pyGHDL stopped with an exception instead.

pyGHDL: exit statement handling is missing

---

pyGHDL/dom/_Translate.py

According to §3.1, range can be a range expression or an attribute name. This must be respected when accessing the fields of the node. Trying to access the range expression fields on an attribute name node led to a libGHDL exception.
The bug is triggered by declarations using an attribute name as range:
```
signal int : integer range entries'range;
```

pyGHDL: fix range handling in subtype indication

---

pyGHDL/cli/requirements.txt
pyGHDL/dom/Attribute.py
pyGHDL/dom/Concurrent.py
pyGHDL/dom/DesignUnit.py
pyGHDL/dom/Expression.py
pyGHDL/dom/NonStandard.py
pyGHDL/dom/Sequential.py
pyGHDL/dom/Subprogram.py
pyGHDL/dom/Symbol.py
pyGHDL/dom/Type.py
pyGHDL/dom/_Translate.py
pyGHDL/dom/_Utils.py
pyGHDL/dom/formatting/GraphML.py
pyGHDL/dom/requirements.txt
testsuite/pyunit/dom/Expressions.py
testsuite/requirements.txt

* The translation process from Iir to DOM now generates `***Symbol` instances, which are wrapping `***Name` instances. This feature was reintroduced in pyVHDLModel v0.25.0 after it was remove to simplify the handling of symbols and names. But VHDL/pyVHDLModel#70 demonstrated, that the former complexity was needed.
* Renamed `GetNameFromNode` to `GetName`. This helper function walks a linked list of names and translates them to a chain of `***Name` instances.
* Removed `Get***Symbol` helper functions.
* Bumped dependencies.
* VHDL/pyVHDLModel#70
* #2308
* #2408

pyGHDL: Reworked Symbols and Names

---

Makefile.in
configure

Archiver on most UNIX-like systems is bound to the GCC distribution we need do allow AR to be configured to prevent leaking of other "ar" executables from path and pick the correct verion from (mostly) GCC.
This is very helpful for downstream packagers of GHDL to ensure correct compilation.

allow redefining the ar executable

---

src/simul/simul-fst.adb

Hi,
I noticed that ghdl crashed when called with an incorrectly formatted "--fst" cmdline option (e.g. without "=" between the option and the filename). The reported error was "CONSTRAINT_ERROR : simul-fst.adb:212 index check failed". This commit fixes this small problem.
BR,
Stanislav

Fix a crash when called with incorrectly formatted "--fst" cmdline option

---

src/vhdl/vhdl-scanner.adb

After I had read the VHDL 93 LRM, I noticed the replacement characters were not supported anymore since VHDL 2008. Didn't know that!
So here are some minor fixes in the code to add a better support.
Changes:
- prevent from using '!' as a '|'
- update pragma for replacement char "%"
@tgingold I think we should also add a pragma for the use of colon ':' in string litteral but I dont know how you want to proceed. Feel free to edit this PR or give me some insights...

Remove replacement characters since VHDL 2008

---

ghw/libghw.c
ghw/libghw.h

This PR adds a flag if all the signals in the `h->sigs` array (other than the entry with index 0) have a non-NULL type.
In that case, the linear search in `ghw_read_hie` can be replaced by a simple addition.
This seems to be the regular case and provides a massive speedup (about 6x to 20x+ in a quick test) in gtkwave.
I've also added some checks for out-of-bounds accesses.
**Context**
I hope that this is the correct place to put these changes to libghw.
Otherwise, I can instead submit them to gtkwave first.
This PR is similar to the patch from #2548, in which the addition is used unconditionally.
Here's that patch without the white space changes: [output.diff.zip](https://github.com/ghdl/ghdl/files/13929182/output.diff.zip)
I'm not sure if it's possible to have a case …

libghw: Speed up ghw_read_cycle_cont without null-type signals

---

scripts/vendors/compile-lattice.ps1

fix #2588 
Implemenation: 
`ecp5u` and `ecp5um` share the same lib. As GHDL looks for paths the `ecp5u` lib is duplicated to `ecp5um` directory and  the .cf file gets `ecp5um` name. To keep things simple, if `ecp5` is selected, both `ecp5u` and `ecp5um` libs are created.
I made and checked the changes for the .ps1 compile-lattice script:
```
C:\GHDL_3_0\lib\ghdl\vendors> .\compile-lattice.ps1 -ecp5
Calling Get-Command ...
Creating vendor directory: 'C:\GHDL_3_0\lib\ghdl\vendors\lattice'.
Compiling library 'ecp5u' ...
Compiling library 'ecp5um' ...
--------------------------------------------------------------------------------
Compiling Lattice libraries [SUCCESSFUL]
```
The following code does not cause errors anymore:  
```vhdl
library ecp5um;
use ecp5um.components.all; …
```

 Add support for ecp5um to vendors\compile-lattice script #2588 

---

ghw/libghw.c
ghw/libghw.h

This MR adds checks to prevent memory access issues when opening ghw files. The type of fixed issues include:
-  Out-of-bounds accesses in arrays (with the array size and index read from the ghw file).
-  Casts to union members without checking the type.
-  Continued program execution after an error condition.
-  Overflows/underflows on malloc size variables.
I've added a function `ghw_error_exit_line` that's called when an invalid value is detected. I've chosen to call `exit(1)` in that case, after printing the . The original code had calls to `abort()` in some cases, I can also change it to do call `abort()`, if you prefer.
Note: codacy fails, but I did not change those lines.

libghw - Add checks to prevent memory access issues when opening ghd files

---

Makefile.in

update Makefile to accept GCC 14, which is the system compiler in Fedora 40
But
````
touch gcc/vhdl/lang.opt.urls
````
workaround is still required to overcome
````
...
make[2]: *** No rule to make target '../../gcc/vhdl/lang.opt.urls', needed by 's-options'.  Stop.
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/builddir/build/BUILD/gcc-14.0.1-20240208/obj-ppc64le-fedora_ghdl-linux/gcc'
make[1]: *** [Makefile:4678: all-gcc] Error 2
make[1]: *** Waiting for unfinished jobs....
````
Seems the `vhdl` backend in GCC will need a little update in the buildsystem to not require the missing file. I believe there is a way, because not all existing backends provide the `lang.opt.urls` file.

update for GCC 14

---

src/grt/grt-processes.adb
src/grt/grt-processes.ads
src/grt/grt-signals.adb

Whenever a source is added to a signal, check the number of sources after adding it. Upon detecting the presence of multiple drivers, display the drivers. Port sources are not displayed because I could not figure out how to exercise this path, though I report their presence if found.
This is an enhancement, and is not related to an issue.

Display the list of all drivers of a signal in case an unresolved signal has multiple drivers.

---

src/grt/grt-callbacks.adb
src/grt/grt-callbacks.ads
src/grt/grt-cvpi.c
src/grt/grt-options.adb
src/grt/grt-options.ads
src/grt/grt-vpi.adb
src/grt/grt-vpi.ads
testsuite/vpi/vpi006/mydesign.vhdl
testsuite/vpi/vpi006/testsuite.sh
testsuite/vpi/vpi006/vpi1.c
testsuite/vpi/vpi007/mydesign.vhdl
testsuite/vpi/vpi007/testsuite.sh
testsuite/vpi/vpi007/vpi1.c
testsuite/vpi/vpi008/mydesign.vhdl
testsuite/vpi/vpi008/testsuite.sh
testsuite/vpi/vpi008/vpi1.c

Implement some additional parts of VPI: vpiVectorVal, vpiScaledRealTime and vpiSuppressTime; setting time and value in value change callbacks; and handle cbAfterDelay in vpi_remove_cb().  Tests included. It also includes PR #2648: "Partial merge of #762: VPI: Adding vpiPort detection (Corrects regression introduced by #753)" as these changes work together.
The use case is integration with Ngspice: with these changes a shared library built by GHDL can define the behaviour of a circuit element in a mixed-signal simulation.

VPI enhancements

---

Makefile.in

Modifies Makefile.in to properly remove all files. Modification was added to uninstall.libghdl as it is what I currently beelive is the most suitable location.
This allows for a complete uninstall without leaving any files behind to close #2316

Modifies uninstall for Uninstall leaves files on disk #2316

---

README.md
doc/getting.rst
doc/ghdl.texi

-------
It is possible now to use Guix to install ghdl binaries (clang backend only).
An example log of its use: https://builds.sr.ht/~csantosb/job/1371825

Add guix as a package manager providing ghdl binaries

---

.github/workflows/Build-Ubuntu.yml
.github/workflows/Package-Docker.yml
.github/workflows/Pipeline.yml

* Updated used pipeline templates to `pyTooling/Actions@r2`
* Run Test Result Publishing not in pull request pipelines.
* Reactivated Docker image building and Docker image checking (execute GHDL's testsuite inside).
* Skip Docker image pushing in pull-request pipelines.

Further pipeline improvements

---

.github/workflows/Build-MSYS2.yml
.github/workflows/Pipeline.yml

This PR enhances the upload of pipeline artifacts from "nightly" tagged builds as assets to the "nightly" release page.
Pipeline to review for tag `testing`: https://github.com/Paebbels/ghdl/actions/runs/12056535122  
Matching release page `testing`: https://github.com/Paebbels/ghdl/releases/tag/testing
**Features:**
* run "Nightly" job only on tagged pipeline runs
* Set name of the release: "nightly"
* Set artifacts to upload as assets (release attachments)
* Format: `artifact:asset:title`
* Asset names can contain leading whitespace, which will be trimmed
* Titles can contain leading whitespace, which will be trimmed
* Asset names starting with ! and ending with zip e.g. `!document.zip` will result in a compressed archive of the mentioned artifact.
* Similar for tar/gz using …

New nightly releases

---

.github/workflows/Pipeline.yml

Currently, TAR/GZ archives have `bin`, `lib`, ... as root directories in the tarball.
As I learned today, a convention enforces archive creates to add a single root-directory into the tarball, which has the same name as the archive, so at decompression, users don't need to create a directory.
> I my opinion this is a still and almost dumb convention, we need to follow this convention ...
Therefore, the job template used in the pipeline supports a new mode, so artifacts packages as an archive can be packaged with such a single root-directory.
**Modifications:**
* Renamed `*.tgz` to `*.tar.gz` (this will match the files from MSYS2/Pacman `*.tar.zst`.
* Package macOS and Ubuntu build results in TAR/GZ archives with a single root-directory.

Pipeline finetuning

---

.github/workflows/Package-Docker.yml
.github/workflows/Parameters.yml
.github/workflows/Pipeline.yml

This PR will use the latest NightlyRelease job template, which supports replacements.
See evidence of the individual steps:
1. extraction of GHDL's version and formatting for ghdl, pyghdl and pacman:  
https://github.com/Paebbels/ghdl/actions/runs/12109215420/job/33758082405#step:4:7
```
ghdl_version:    5.0.0-dev
pyghdl_version:  5.0.0.dev0
pacghdl_version: 5.0.0.dev-1
```
2. Running the pipeline at paebbels/ghdl with tag testing: https://github.com/Paebbels/ghdl/actions/runs/12109731158
3. checking release 'testing': https://github.com/Paebbels/ghdl/releases/tag/testing

Replace hardcoded versions with placeholders.

---

.github/workflows/Pipeline.yml

This PR uses the latest NightlyRelease job template from pyTooling, which generates a so called Release Inventory in JSON format.
Each asset can be marked with several categories like `ubuntu`/`macos`/`windows`, `24.04`/`13`/`2022`, `x86-64`/`aarch64`, `mcode`/`llvm`, ... This allows us to decouple the `setup-ghdl` Action from nightly releases at GHDL. Especially, when nightly changes from 5.0.0-dev to 6.0.0-dev, no update/new release of `setup-ghdl` will be required.
The information in the JSON file can be queried by `jq`, a command-line query tool available in GitHub Actions. We can ask for "ubuntu.2022.x86-64.native.llvm" and it will tell us the filename of the matching GHDL installation.
Tested at Paebbels/ghdl:
* Pipeline: https://github.com/Paebbels/ghdl/actions/runs/12775822373
* …

Generate an inventory.json as a release asset.

---

.github/workflows/Build-MSYS2.yml
.github/workflows/Build-MacOS.yml
.github/workflows/Build-Ubuntu.yml
.github/workflows/Package-pyGHDL.yml
.github/workflows/Pipeline.yml
.github/workflows/Publish-GitHubPages.yml
.github/workflows/Test-SetupGHDL.yml
doc/requirements.txt
testsuite/requirements.txt

This PR will add a test using `setup-ghdl` using release assets from nightly releases. In case the nightly release asset upload is broken, we can immediately identify if dozens to hundreds of GitHub pipeline using `setup-ghdl` might be broken. GHDL is installed in all variants and the version number is verified. Each installation takes just a few seconds. No test cases are executed.
* Install uploaded asset files provided by a nightly release using `setup-ghdl@v1`.
* Set release page title for nightly release to a fixed value  
(currently, it shows nightly plus commit title).
* Improved YAML coding style.
* Bumped dependencies.

Add setup-ghdl testing to pipeline

---

pyGHDL/cli/requirements.txt
pyGHDL/libghdl/requirements.txt
pyproject.toml
testsuite/pyunit/dom/StopWatch.py

* Bumped dependencies.  
Fixes #2870.
* Fixed testcase `CompileOrder.test_Encoder`, so compile order can be iterated.

pyGHDL: Fixed testcase to iterate the compile order

---

.github/workflows/Package-Docker.yml

This PR added [standardized labels](https://github.com/opencontainers/image-spec/blob/main/annotations.md) to the generated Docker images, so GHDL's Docker images will be ready for attestation and Docker container scanning (checking for vulnerabilities and outdated applications or libraries in the container).
Added labels:
* org.opencontainers.image.vendor
* org.opencontainers.image.authors
* org.opencontainers.image.url
* org.opencontainers.image.documentation
* org.opencontainers.image.source
* org.opencontainers.image.revision
* org.opencontainers.image.version
* org.opencontainers.image.description
A debug step was added for printing and formatting all applied labels of the image.  
Here the results from a run of `Paebbels/ghdl`:
@tgingold please check the used values for the vendor …

Make GHDL's Docker images ready for attestation and Docker container scanning

---

.github/workflows/Pipeline.yml
.github/workflows/Test-SetupGHDL.yml

When the testing of `setup-ghdl` was added to the pipeline, the matrix got accidentally added as a nested matrix. Ideally, all matrix descriptions should be in the top-level YAML to ease control.
This PR fixes that behavior and brings the nested matrix to the top-level YAML file.
* Improved YAML coding style
* Moved nested matrix of `Test-SetupGHDL.yml` to `Pipeline.yml`.
The pipeline is currently tested in Paebbels/ghdl: https://github.com/Paebbels/ghdl/actions/runs/13229282625 using tag `testing`.

Fix the setup-ghdl matrix

---

.github/workflows/Build-MSYS2.yml

This PR fixes the missing version information in MSYS2/* builds by installing Git in MSYS2.
Fixes #2889.

Install Git in MSYS2, so binaries contain Git version information.

---

.github/workflows/Build-MSYS2.yml
.github/workflows/Build-MacOS.yml
.github/workflows/Package-pyGHDL.yml
.github/workflows/Parameters.yml
.github/workflows/Pipeline.yml
.github/workflows/Test-GHDL.yml
.github/workflows/Test-SetupGHDL.yml

This PR will add the packaging of pyGHDL for MinGW64 and UCRT64 as platform specific wheel packages.
Steps:

Package pyGHDL for MSYS2 runtimes MinGW64 and UCRT64

---

pyGHDL/dom/NonStandard.py
pyGHDL/dom/requirements.txt
testsuite/pyunit/dom/Expressions.py
testsuite/pyunit/dom/Literals.py
testsuite/pyunit/dom/Simple.py

* Added an option to allow setting up different IEEE flavors when setting up a design with `pyGHDL.dom`.  
`design.LoadDefaultLibraries(IEEEFlavor.Synopsys)`
* Replace local implementations of `firstValue` by a common implementation from `pyTooling.Common`
* Bumped dependencies: pyVHDLModel to v0.30.0.
* Fixes #2886
* Fixes #2887.

Added IEEE flavor option when setting up a design in pyGHDL.dom

---

.github/workflows/Pipeline.yml

This PR adds macOS-15 assets to the asset list of the nightly release. It was tested on `Paebbels/ghdl` using tag `testing`. The pipeline failed, because the `inventory.json` file for `setup-ghdl` is loaded from `ghdl/ghdl` and not from `Paebbels/ghdl`.

Add macOS-15 assets to the asset list of the nightly release

---

ghw/libghw.c

While testing some changes in GTKWave I've noticed that libghw didn't read values of type `ghdl_rtik_type_i64` and instead printed this error message:
```
read_value: cannot handle format 26
```
This error was also reproducible by using `ghwdump` from a recent GHDL version.
Adding the `ghdl_rtik_type_i64` case statement fixed the issue. I'm not familiar with the internals of libghw, but `i32` and `p32` are handled the same way, which makes me believe that this fix is correct.
VHDL file to generate a GHW file to trigger the issue:
```vhdl
entity ghw_issue is
begin
end;
architecture beh of ghw_issue is
type i64 is range 0 to 4000000000;
signal sig_i64 : i64;
begin
end;
```
I didn't see any unit tests related to libghw that would need to be updated, but let me know if I missed something.

ghw: handle i64 in ghw_read_value

---

.github/workflows/Package-pyGHDL.yml
.github/workflows/Pipeline.yml
pyGHDL/cli/requirements.txt
pyGHDL/libghdl/requirements.txt
pyproject.toml
testsuite/requirements.txt

* Bumped dependencies
* Changed pyGHDL package name, because PyPA change the normalization rules for package names.
* #2972 
* #2973

Fix issues with pyGHDL package name

---

Makefile.in
src/ortho/gcc/ortho-lang-15.c

The usual version bump for GCC 15. But this time we need a change to `ortho-lang-9.c` caused by https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=55947b32c38a. The "ortho-lang" change itself look like https://src.fedoraproject.org/rpms/ghdl/blob/rawhide/f/ghdl-gcc15-ortho.patch
I suppose we want to fork the `ortho-lang-9.c` to `ortho-lang-15.c`, because it's not compatible with older gcc. And when doing that, we probably want to switch to the C++ filename as well, so `ortho-lang-15.cc` will be added and the `Makefile.in` updated appropriately. What do you think?

update for GCC 15

---

ghw/libghw.c
ghw/libghw.h

This pr adds a signal index cache in libghw to drastically speed-up (especially in gtkwave) loading of big ghw files when null signals are present. 
The current algorithm parses again the list at every request, while this method improves performances.
The cache is then freed upon closure of the ghw file being loaded.

[libghw/performance] Improves the performance of loading big ghw files
