ghdl/ghdl

doc/Invoking_GHDL.rst
doc/ghdl.texi

Document bind only (-b) option to make (-m) command from commit 876bf7fea6d.

---

doc/Invoking_GHDL.rst
doc/Starting_with_GHDL.rst

I was puzzled until I read `BUILDING.txt`. This should get people there faster.

Document GCC backend needed to generate executables

---

libraries/vendors/compile-altera.sh
libraries/vendors/compile-lattice.sh
libraries/vendors/compile-osvvm.sh
libraries/vendors/compile-vunit.sh
libraries/vendors/compile-xilinx-ise.sh
libraries/vendors/compile-xilinx-vivado.sh
libraries/vendors/config.sh
libraries/vendors/shared.sh

Implemented a work around for Mac OS.
Changes:
- `#! /bin/bash` changed to `#! /usr/bin/env bash`
- Set `$READLINK` to `greadlink` if it's a Dawrin system
- Replaced `readlink` with `$READLINK`
- Fixed ANSI coloring

Implemented a work around for Mac OS.

---

libraries/vendors/README.md
libraries/vendors/compile-altera.ps1
libraries/vendors/compile-altera.sh
libraries/vendors/compile-lattice.ps1
libraries/vendors/compile-lattice.sh
libraries/vendors/shared.psm1
libraries/vendors/shared.sh

This pull request depends on #94.
This pull request changes:
- Added missing Lattice compile script.
- Enabled VHDL-2008 compilation in all vendor library compile scripts, since VHDL-2008 flavor synopsys is working.
- Updated README.md.
Regards
Patrick

Added missing Lattice compile script.

---

dist/mcode/winbuild.ps1

Hello,
This commit adds support for:
* install into:
* default directory,
* user defined directory,
* install into same directory as last time, if `InstallDir.conf` exists,
* update into same directory as last time and
* uninstall.
```PowerShell
.\winbuild.ps1 -Install
.\winbuild.ps1 -Install C:\Tools\GHDL\0.34dev
.\winbuild.ps1 -Install
.\winbuild.ps1 -Update
.\winbuild.ps1 -Uninstall
```
The new behavior is similar to `./configure --prefix=path/to/ghdl`. The mentioned `InstallDir.conf` file is save into the build directory.
Note: You might have to apply merge #169 before this one.

Added support for install into default directory, install into same directory, update and uninstall.

---

doc/Simulation_and_runtime.rst
src/grt/grt-errors.adb
src/grt/grt-errors.ads
src/grt/grt-fst.adb
src/grt/grt-vcd.adb
src/grt/grt-wave_opt-design.adb
src/grt/grt-wave_opt-design.ads
src/grt/grt-wave_opt-file-debug.adb
src/grt/grt-wave_opt-file.adb
src/grt/grt-wave_opt-file.ads
src/grt/grt-wave_opt.adb
src/grt/grt-wave_opt.ads
src/grt/grt-waves.adb

Support added for * and **. Please note that wildcards inside names like /top/sub*/... are not supported yet, only synthax like /top/*/... works for now. Support for wildcards inside names will be added on version 1.2, at the same time as simple regexp support.
Current version set to 1.1

Support added for * and **. Current version set to 1.1

---

src/grt/grt-vpi.adb

allow cleanup of vpi objects to avoid memory leaks

implement vpi_free_object

---

libraries/vendors/compile-uvvm.ps1

This pull request changes:
* moves file list into an associative array
* removes redundant code

Updated pre-compile script for UVVM.

---

dist/windows/InstallerTemplate.ps1
dist/windows/compile.ps1

This pull request changes:
* Existing directories are now removed before updating.
* The ZIP extraction shows now a progress bar.

Fixed file overwrite problem.

---

src/grt/ghwdump.c
src/grt/ghwlib.c
src/grt/ghwlib.h

Implement @tgingold suggestiongs from #334

Move skip flags to own arry in ghwlib + indent new code to indigenous style

---

dist/windows/InstallerTemplate.ps1
dist/windows/compile.ps1
libraries/vendors/compile-intel.ps1
libraries/vendors/compile-intel.sh
libraries/vendors/compile-lattice.ps1
libraries/vendors/compile-osvvm.ps1
libraries/vendors/compile-uvvm.ps1
libraries/vendors/compile-uvvm.sh
libraries/vendors/compile-vunit.ps1
libraries/vendors/compile-xilinx-ise.ps1
libraries/vendors/compile-xilinx-vivado.ps1
libraries/vendors/config.psm1
libraries/vendors/config.sh
libraries/vendors/shared.psm1

**This pull-request:**
- Adds more verification IPs (VIP) to the UVVM pre-compilation script
- The UVVM pre-compile script is based on `compile_order.txt` files for each VIP
- Minor improvements and bug fixes to the PowerShell scripts
- Added pre-compile script for Intel-FPGA
- Allow silent installation with the new option `-AddToPath` available in:
* `compile.ps1`, and
* the generated *.ps1 installer file.

Improved build and pre-compile scripts

---

doc/Invoking_GHDL.rst
src/ghdldrv/ghdldrv.adb

This commit is a simple extension on top of gen-makefile.
I am not sure, if this functionality is needed or not for ghdl.
However I wanted it for a project, so why not publish it...
This is my first Ada commit, so please hit me with improvements.

add gen-depends command for dependency file generation

---

.gitignore

fix gitignore filters for files generated on windows

---

libraries/vendors/compile-xilinx-vivado.sh

Fixed default path in vivado libraries compilation script

---

doc/shields.inc

fix appveyor shield on rtd

---

dist/windows/compile-ghdl.ps1
dist/windows/compile-libraries.ps1

Fixed library compilation on Windows due to changes in 7ef79a53.

Fixed library compilation on Windows

---

configure

This PR:
* fixes indentations in the configure script.
* adds missing license text.

Improvements to configure.sh

---

doc/building/gcc/GNULinux-GNAT.rst
doc/ghdl.texi

#754 changed directory to build ghdl libraries

minor change in GCC backend build example

---

doc/index.rst

Update the index of the docs to add the two latest releases to the news.

add announcements for 20181129 and v0.36-rc1

---

src/synth/netlists.ads

My first contribution haha
Reading the synth code to understand how stuff works.
SO MANY QUESTIONS.
Comments are very helpful.

Small typo in netlist.ads

---

.github/CODE_OF_CONDUCT.md

I have added the [No Code Of Conduct](https://github.com/domgetter/NCoC) to the project. Resolves #841.
:rotating_light: Before submitting your PR, please read [contribute](http://ghdl.readthedocs.io/en/latest/contribute.html#fork-modify-and-pull-request) in the [Docs](http://ghdl.readthedocs.io/en/latest/index.html), and review the following checklist:
I created the *CODE_OF_CONDUCT.md* file in the *.github/* directory as I have though that it is the most appropriate directory considering the current project structure. However, if you want to move the file, feel free to do so. If you have any comments, let me know.

Add a code of conduct

---

dist/travis/travis-ci.sh

I did several modifications in ghdl/docker to simplify docker image names. Now:
- Images are not tagged `*mcode` and `*mcode-gpl`, the former is used only. It is fixed for this repo in #862.
- `ghdl/build:*gcc` and `ghdl/run:*gcc` images no longer have the version as a suffix. This PR is to fix this.

fix: *gcc* build and run docker images are now named *gcc

---

src/synth/synth-expr.adb

This PR allows synthesizing the length attribute of arrays.

handle array attribute "length"

---

src/synth/synth-expr.adb
testsuite/synth/physical01/physical_division.vhdl
testsuite/synth/physical01/testsuite.sh

This PR implements the division of two physical numbers, which yields an integer.

synth: add physical division

---

configure
doc/getting/LLVM.rst

If the feature changes current behaviour, explain why your solution is better.
:rotating_light: Before submitting your PR, please read [contribute](http://ghdl.readthedocs.io/en/latest/contribute.html#fork-modify-and-pull-request) in the [Docs](http://ghdl.readthedocs.io/en/latest/index.html), and review the following checklist:

enable llvm9

---

src/synth/synth-oper.adb

A small step in #903 
Was it really this simple... you know how you always get suspicious when it works first try...

Add record (in)equality

---

configure

fix(configure): use '/dev/null' to check 'cmp', use 'sed' to compare versions

---

Makefile.in

makefile: remove 'check' target

---

configure

configure: fix typo

---

doc/examples/quick_start/heartbeat/README.rst

doc(heartbeat): fix position of arg '--wave'

---

testsuite/synth/issue1082/ent.vhdl
testsuite/synth/issue1082/testsuite.sh

In this PR, https://github.com/ghdl/ghdl/pull/1082#issuecomment-573291835 is added as a test.

testsuite/synth: add test from #1082

---

.github/workflows/push.yml
dist/msys2-mingw/run.sh

This PR fixes Windows jobs in GHA.

GHA: fix windows jobs 

---

src/synth/synth-ieee-numeric_std.adb
src/synth/synth-ieee-numeric_std.ads
src/synth/synth-static_oper.adb
testsuite/synth/issue1179/bug.vhdl

Implement ```unsigned * natural``` similar to
```natural * unsigned``` in issue #1179

synth-static_oper: handle mul uns nat.

---

doc/using/Foreign.rst
doc/using/InvokingGHDL.rst
doc/using/Simulation.rst

This PR includes multiple additional tips, hints and clarifications as a result of the conversations in #1184, #1185 and #1059 with regard to building and co-executing VHDL with foreign (C) sources through VHPIDIRECT.
/cc @RocketRoss

doc: update tips/hints related to VHPIDIRECT

---

src/grt/Makefile.inc

Makefiles: fixed race condition in creation of "grt" directory before main.o is put in it

---

doc/using/Simulation.rst

See https://github.com/ghdl/ghdl-cosim/pull/19#discussion_r418431997.

doc: add hint about passing multiple '--vpi='

---

NEWS.md
README.md
doc/index.rst

This PR announces ghdl-yosys-plugin, ghdl-cosim and the wiki in the main doc site. Some other minor fixes to `README.md` and updating `NEWS.md` are included too.

doc: update news

---

testsuite/testenv.sh

Replace tabs with spaces.
Unify indentation to 2 spaces.

Improve formatting of testenv.sh file.

---

doc/internals/rti.rst

I created some documentation on the RTI nodes mostly for my own benefit.  I'm hoping that as I add more comments to the code, this document will be become unnecessary.

WIP: Add some documentation on the RTI structures.

---

src/grt/grt-vpi.adb
testsuite/vpi/vpi004/mydesign.vhdl
testsuite/vpi/vpi004/testsuite.sh
testsuite/vpi/vpi004/vpi1.c

Implement the rest of #1396 by adding **argc** and **argv** to `vpi_get_vlog_info()`.

VPI: Add argc/argv to vpi_get_vlog_info()

---

src/synth/synth-oper.adb
testsuite/synth/enum01/tb_test.vhdl
testsuite/synth/enum01/test.vhdl
testsuite/synth/enum01/test_pkg.vhdl
testsuite/synth/enum01/testsuite.sh

If the feature changes current behaviour, explain why your solution is better.

synth-oper: Support Iir_Predefined_Enum_Greater{,_Equal}

---

doc/requirements.txt
pyGHDL/__init__.py
pyGHDL/cli/__init__.py
pyGHDL/cli/ghdl-ls
pyGHDL/dom/Common.py
pyGHDL/dom/DesignUnit.py
pyGHDL/dom/InterfaceItem.py
pyGHDL/dom/Misc.py
pyGHDL/dom/__init__.py
pyGHDL/libghdl/__init__.py
pyGHDL/libghdl/utils/__init__.py
setup.py
testsuite/.coveragerc
testsuite/pyunit/SimpleEntity.vhdl
testsuite/pyunit/SimplePackage.vhdl

Splitting #1562:
* File headers and license texts.

Added file headers and license texts.

---

pyGHDL/libghdl/__init__.py

This is split from #1562 and brings:
* Updated docstrings
* Using [pathlib](https://docs.python.org/3/library/pathlib.html) instead of os.path.  
e.g. `absolute(join(dir, "..", "..", "lib"))` becomes `(dir / "../../lib").resolve()`
* Add exception handling instead of None checks.

Modifications to pyGHDL.libghdl

---

pyGHDL/libghdl/utils/__init__.py

This is a split from #1562 and fixes or adds:
* Type annotations
* Fixed imports (unused imports)
* Object references
* Changes assert /which raises an AssertionException) to a regular Exceptions.
* Modified docstrings to use restructured text roles for processing by Sphinx.

Modifications to pyGHDL.libghdl.utils

---

pyGHDL/libghdl/errorout.py
pyGHDL/libghdl/std_names.py
pyGHDL/libghdl/vhdl/elocations.py
pyGHDL/libghdl/vhdl/nodes.py
pyGHDL/libghdl/vhdl/nodes_meta.py
pyGHDL/libghdl/vhdl/tokens.py
scripts/pnodespy.py

This PR modifies `pnodespy.py` to add an *auto-generated* note as a file header.
In addition, all 6 auto generated Python files where updated.
---------
This is ready for review.

Add file headers to auto-generated Python sources.

---

.github/workflows/push.yml
testsuite/pyunit/dom/SimplePackage.py
testsuite/pyunit/pytest.ini
testsuite/testsuite.sh

This is split from #1562:
* activate coverage collection
* new SimplePackage test case

pyGHDL: Remaining changes

---

libraries/vendors/compile-altera.sh
libraries/vendors/compile-intel.sh
libraries/vendors/compile-lattice.sh
libraries/vendors/compile-osvvm.sh
libraries/vendors/compile-uvvm.sh
libraries/vendors/compile-xilinx-ise.sh
libraries/vendors/compile-xilinx-vivado.sh
libraries/vendors/shared.sh

This PR fixes potential bugs in Bash scripts.
They where reported by Bash Support Pro in PyCharm as warnings, style issue or potential bugs.

Fixed style issues and potential bugs.

---

libraries/vendors/compile-uvvm.ps1

With this PR, the PowerShell based pre-compile script reads order of UVVM components from `component_list.txt`.
This is ready for merge.
-------------
Thanks to @tpcorrea and his discussion in Gitter: https://gitter.im/ghdl1/Lobby?at=600397e3787d8f79c8083068

Read order of components from UVVM repository.

---

src/grt/vpi_user.h

This modification is extracted from #762. It updates the `vpi_user.h` header file from IEEE Std 1364-2005 to IEEE Std 1800-207.
/cc @kammoh

update 'vpi_user.h' to IEEE Std 1800-2017

---

doc/development/building/GCC.rst
doc/development/building/index.rst

I updated instructions about GNAT Community Edition installation.

doc: update instructions about GCC and GNAT Community installation

---

src/vhdl/vhdl-prints.adb
src/vhdl/vhdl-sem_names.adb
src/vhdl/vhdl-utils.adb
src/vhdl/vhdl-utils.ads
testsuite/gna/issue1593/element_bug.vhdl
testsuite/gna/issue1593/testsuite.sh

This PR is an attempt to add the `'element` attribute that was mentioned in this issue #1593 
**What is done:**
I have changed some sem files and did a couple of test on vhdl to see if the code compiles and simulate correctly
**What is left to do:**

Add 'element attribute support

---

src/vhdl/vhdl-parse.adb

Resynchronize on end of External name. Search for colon or semicolon

Vhdl parse: resync external name

---

src/flags.ads
testsuite/gna/bug0101/repro1.ref
testsuite/gna/bug063/dff.expected
testsuite/gna/issue719/tb.ref

Set -fcaret-diagnostics to be enabled by default.

Fcaret diagnostics on by default

---

src/grt/grt-vhpi.adb
src/grt/grt-vhpi.ads
testsuite/vhpi/001load_lib/vhpi_lib.c
testsuite/vhpi/002load_entrypoint/vhpi_lib.c
testsuite/vhpi/003load_multi_lib/vhpi_lib1.c
testsuite/vhpi/003load_multi_lib/vhpi_lib2.c
testsuite/vhpi/004trace_stdout/mydesign.vhdl
testsuite/vhpi/004trace_stdout/testsuite.sh
testsuite/vhpi/004trace_stdout/vhpi_lib.c
testsuite/vhpi/005trace_file/mydesign.vhdl
testsuite/vhpi/005trace_file/testsuite.sh
testsuite/vhpi/005trace_file/vhpi_lib.c

Add VHPI tracing.
Reference #1648.

VHPI: add tracing

---

src/grt/grt-avhpi.ads
src/grt/grt-vhpi.adb
src/grt/grt-vhpi.ads

Improve interop with C enums, per discussion in #1728.

VHPI: improve C enum interop

---

scripts/vendors/compile-uvvm.ps1
scripts/vendors/compile-uvvm.sh

Do not merge it yet, as I am still fighting with the UVVM to move the bitvis_vip_wishbone from UVVM_Community to UVVM repository https://github.com/UVVM/UVVM/issues/131. However, with PR available anyone can easily fetch it.

Add option to compile UVVM Wishbone VIP.

---

pyGHDL/lsp/symbols.py

**Changes**
* Remove duplicate keys in dictionary.

[LSP] Removed duplicate keys in dictionary

---

.editorconfig

**Enhancements** 
This adds an editor configuration file for:
* Python sources
* PowerShell sources
* YAML config files
* JSON files
* INI files
* Markdown files
* ReStructureText files
This will ensure a minimal standard for users with different editors to use same rules for indentation, tab-style, tab-sizes, ...
**Content:**
```ini
root = true
[*]
charset = utf-8
insert_final_newline = true
trim_trailing_whitespace = true
indent_style = tab
indent_size = 2
tab_width = 2
[*.py]
indent_style = space
indent_size = 4
[*.{ps1, psm1}]
indent_style = tab
indent_size = 2
[*.{yml,yaml}]
indent_style = space
indent_size = 2
[*.{json,ini}]
indent_style = tab
indent_size = 2
[*.md]
trim_trailing_whitespace = false
[*.rst]
indent_style = space
indent_size = 3
```

Added editor configuration file.

---

pyGHDL/dom/DesignUnit.py
pyGHDL/dom/Expression.py
pyGHDL/dom/Literal.py
pyGHDL/dom/Misc.py
pyGHDL/dom/Object.py
pyGHDL/dom/Symbol.py
pyGHDL/dom/_Translate.py
pyGHDL/dom/_Utils.py

* Make creation of objects more local by moving creation code into a classmethod, so `parse` acts as a factory.

Made code more local.

---

pyGHDL/cli/DOM.py
pyGHDL/dom/DesignUnit.py
pyGHDL/dom/Expression.py
pyGHDL/dom/InterfaceItem.py
pyGHDL/dom/Literal.py
pyGHDL/dom/Misc.py
pyGHDL/dom/NonStandard.py
pyGHDL/dom/Object.py
pyGHDL/dom/Subprogram.py
pyGHDL/dom/Symbol.py
pyGHDL/dom/Type.py
pyGHDL/dom/_Translate.py
pyGHDL/dom/_Utils.py
pyGHDL/dom/formatting/prettyprint.py
pyGHDL/requirements.txt
testsuite/pyunit/Current.vhdl
testsuite/pyunit/dom/Expressions.py
testsuite/pyunit/dom/Literals.py
testsuite/pyunit/dom/SimpleEntity.py
testsuite/pyunit/dom/SimplePackage.py

**New Features**
* Add handling of more expression kinds (logical, compare, shift, rotate, rem, mod)
* Added handling of qualified expression
* Added handling of components in declarations.
* Added handling of physical literals (integer and float format)
* Added handling of string literals
* Basic handling function calls (or array indexing)
* Basic handling of aliases
* Basic handling of types and subtypes
* Basic handling of functions and procedures
* Print location (`file:line:column`) where an exception occurs.
* Updated pretty-printing
**Changes:**
* Fixed aggregates
* Renamed utility function `NodeToName` to `GetNameOfNode`

More expression kinds and function calls

---

libraries/openieee/build_1164.py
libraries/openieee/build_numeric.py
pyGHDL/dom/NonStandard.py
pyGHDL/dom/_Utils.py
pyGHDL/libghdl/__init__.py
pyGHDL/libghdl/errorout.py
pyGHDL/libghdl/std_names.py
pyGHDL/libghdl/utils.py
pyGHDL/libghdl/vhdl/elocations.py
pyGHDL/libghdl/vhdl/nodes.py
pyGHDL/libghdl/vhdl/nodes_meta.py
pyGHDL/lsp/lsp.py
pyGHDL/lsp/workspace.py
scripts/pnodespy.py
testsuite/gna/issue43/run.py
testsuite/pyunit/libghdl/Initialize.py
testsuite/pyunit/lsp/LanguageServer.py

This PR fixes several issues reported by Codacy, and `black` is used in `libraries/openieee/*.py`.

Fix codacy issues

---

pyGHDL/libghdl/std_names.py
pyGHDL/libghdl/vhdl/nodes.py
pyGHDL/libghdl/vhdl/tokens.py
pyGHDL/lsp/document.py
pyGHDL/lsp/lsp.py
pyGHDL/lsp/lsptools.py
pyGHDL/lsp/references.py
pyGHDL/lsp/workspace.py
scripts/pnodes.py
scripts/pnodespy.py
testsuite/gna/issue283/example.py

A few more fixes to issues reported by Codacy.

Fix more codacy issues

---

setup.py

This PR fixes issues in `setup.py` and it's the function to read dependencies from `requirements.txt`.
Since last PR for DOM, the `requirements.txt` has been split into multiple files, so users can choose what to install depending on the usecase. Common requirement files are included via `-r ...` option. The new read function can now handle these recursive includes. Same includes are also deduplicated.

Read requirement files recursively

---

NEWS.md
doc/about.rst
doc/development/CodingStyle.rst
doc/development/building/GCC.rst
doc/index.rst

Coming from #1839.
This PR updates the "NEWS" to announce v1.0 (better late than never 😄 ). By the way, some references to readthedocs site are replaced.

doc: announce v1.0

---

src/ortho/mcode/ortho_code-x86-insns.adb
src/vhdl/translate/trans-chap2.adb
src/vhdl/translate/trans.adb
src/vhdl/translate/trans_analyzes.adb
src/vhdl/vhdl-canon.adb
src/vhdl/vhdl-canon.ads
src/vhdl/vhdl-sem_expr.adb
src/vhdl/vhdl-sem_inst.adb
src/vhdl/vhdl-sem_scopes.adb
src/vhdl/vhdl-utils.adb
src/vhdl/vhdl-utils.ads

This fixes some typos found while investigating Python and Ada code.

Fixed some typos.

---

src/vhdl/vhdl-evaluation.adb

Implement the matching operators ?<, ?<=, ?>, ?>=, ?/=.
Added implementations for the matching operators according to the LRM.
Tested against the Compliance Tests and appears to pass.

Implement Matching Operators

---

scripts/vendors/compile-altera.ps1
scripts/vendors/compile-intel.ps1
scripts/vendors/compile-lattice.ps1

**Description** Fixed a broken function call in some PowerShell precompile scripts. Some Lattice and Intel library files failed to compile.
Closes  #1975

Fixed failing vendor library compilation using PoSh scripts

---

doc/about.rst
doc/using/ImplementationOfVHDL.rst

As commented by @Paebbels on https://github.com/ghdl/ghdl/commit/723a80c63b362ffb988ce08abc9a6d10f5a22cea

Fix some docs issues introduced by #1981

---

doc/internals/RTI.rst
doc/internals/index.rst
doc/using/InvokingGHDL.rst

Fix a few typos

---

testsuite/suite_driver.sh

The vests suite is still sequential since it doesn't seem to go through
suite_driver which is still limiting the speedup.

Parallelize suite_driver with xargs -P

---

src/ghdldrv/ghdllocal.adb

Fix #137
Add `-all` option to `--dir` command so that :
```
$ ghdl -a --work=poc foo1.vhdl
$ ghdl -a --work=poc foo2.vhdl
$ ghdl -a --work=work foo3.vhdl
$ ghdl --dir --all
package foo1
package body foo1
entity foo2
architecture rtl of foo2
entity foo3
architecture rtl of foo3  
```

ghdldrv: add --all option to dir command

---

.github/workflows/Test.yml

Investigate CI failure on macosx (llvm)

---

testsuite/pyunit/SimpleEntity.vhdl
testsuite/pyunit/dom/SimpleEntity.py
testsuite/pyunit/libghdl/Initialize.py

This PR enhances the SimpleEntity.vhdl with code comments for later testing.

Enhanced SimpleEntity with code comments.

---

pyGHDL/dom/Attribute.py
pyGHDL/dom/Concurrent.py
pyGHDL/dom/Expression.py
pyGHDL/dom/NonStandard.py
pyGHDL/dom/Sequential.py
pyGHDL/dom/_Translate.py
pyGHDL/dom/_Utils.py
pyGHDL/dom/formatting/prettyprint.py
pyGHDL/libghdl/__init__.py
pyGHDL/libghdl/errorout_memory.py
pyGHDL/libghdl/files_map_editor.py
pyGHDL/libghdl/name_table.py
pyGHDL/libghdl/str_table.py

* Allow the configuration of `ENCODING`. Default is `latin-1`/`iso-8859-1`.
* Improved f-strings.
* Fixed some typos.
* Clear errors after checking for errors.

Configurable encoding for pyGHDL

---

doc/_templates/autoapi/module.rst
doc/conf.py
doc/prolog.inc

* Added `pycode` rule for inline syntax highlighting.
* Updated autoapi template (for Python documentation extraction from Python source files).
* Changed pygments style from `stata-dark` to `manni` for lighter colors / no dark mode.
* Reduced usage of patched Sphinx plugins.
* Adjusted colors for dependency diagrams.
* Fixed intersphinx URL for Python 3.

Sphinx updates

---

src/grt/grt-signals.adb
testsuite/gna/issue2575/test.vhdl
testsuite/gna/issue2575/testsuite.sh

Bugfix for issue #2575

---

NEWS.md
README.md

Hello
I fixed several spelling issues.

Docs fix spelling issues

---

pyGHDL/dom/formatting/GraphML.py

* Improved class hierarchy for formatters.

Improved GraphML formatting.

---

.github/workflows/Test-GHDL.yml
doc/getting.rst
pyGHDL/dom/_Translate.py
pyGHDL/dom/__init__.py
pyGHDL/dom/requirements.txt
setup.py
testsuite/requirements.txt

* [Removed pipeline debugging code.](https://github.com/ghdl/ghdl/commit/a4c0d36db2040c065b5c0f54263b29ff2fdd485c)
* [Renamed iterator variable from generic to item.](https://github.com/ghdl/ghdl/commit/779630366ac1cba463afc71753d19265241ab95f)
* [Bumped dependency to pyVHDLModel.](https://github.com/ghdl/ghdl/commit/00621e96eebfdd346d00c5f715a3d25ce9a4edae)
* [Fixed initialization of _position in DOMMixIn.](https://github.com/ghdl/ghdl/commit/ea0fd80e8d53781c60f91d82f6705770cb8539e7)
* [Fixed syntax error in documentation.](https://github.com/ghdl/ghdl/commit/00c64977aacf2dfb6943eb2e226a5cbf0ce22f5c)

Cleanups and preparations for pyGHDL updates

---

pyGHDL/__init__.py
pyGHDL/dom/Attribute.py
pyGHDL/dom/DesignUnit.py
pyGHDL/dom/Name.py
pyGHDL/dom/NonStandard.py
pyGHDL/dom/Object.py
pyGHDL/dom/Symbol.py
pyGHDL/dom/Type.py
pyGHDL/dom/_Translate.py
pyGHDL/dom/_Utils.py
pyGHDL/dom/__init__.py
pyGHDL/dom/formatting/prettyprint.py
pyGHDL/libghdl/_types.py

* [Fixed access to property Identifier in pretty-printing algorithm.](https://github.com/ghdl/ghdl/commit/8aaf9675454f3267918888aab1fc54aef5ba141c)
* Renamed `pyGHDL.dom.Names` → `pyGHDL.dom.Name`
* [Added doc-strings.](https://github.com/ghdl/ghdl/commit/b1023b023b5b352c2b3d9c55a8908598322ef77b)

More doc-strings for pyGHDL

---

pyGHDL/dom/NonStandard.py
pyGHDL/libghdl/files_map.py
src/files_map.ads

* [Added Find_Source_File to Python bindings.](https://github.com/ghdl/ghdl/commit/fbb70ac14a763ad2945eec0b0e202c6b7c69e9ae)
* [Improved error handling and reporting when loading VHDL files.](https://github.com/ghdl/ghdl/commit/5affa2e965e5a68da53d051fff538cd722315121)

Expose Find_Source_File to Python binding

---

pyGHDL/cli/dom.py

* Support `-L`/`--library` in the DOM CLI test program.

Add --library argument to DOM test program

---

pyGHDL/__init__.py
pyGHDL/dom/Aggregates.py
pyGHDL/dom/Attribute.py
pyGHDL/dom/Concurrent.py
pyGHDL/dom/DesignUnit.py
pyGHDL/dom/Expression.py
pyGHDL/dom/InterfaceItem.py
pyGHDL/dom/Literal.py
pyGHDL/dom/Misc.py
pyGHDL/dom/Name.py
pyGHDL/dom/NonStandard.py
pyGHDL/dom/Object.py
pyGHDL/dom/PSL.py
pyGHDL/dom/Sequential.py
pyGHDL/dom/Subprogram.py
pyGHDL/dom/Symbol.py
pyGHDL/dom/Type.py
pyGHDL/dom/_Translate.py
pyGHDL/dom/_Utils.py
pyGHDL/dom/__init__.py
pyGHDL/dom/formatting/prettyprint.py
pyGHDL/libghdl/_types.py

To avoid conflicts, please merge #2841, #2842, #2843 before this PR.
* [Added missing `None` return type for functions without return value.](https://github.com/ghdl/ghdl/commit/2e68c3a8a367f215fc02ff6b06e5af397c1ef273)

pyGHDL updates

---

.github/workflows/Parameters.yml
.github/workflows/Pipeline.yml

*  Disabled pre-release release page state for real releases.
* Fix nightly pattern.

Minor pipeline fixes.

---

.github/workflows/Package-pyGHDL.yml
pyGHDL/dom/Attribute.py
pyGHDL/dom/Literal.py
pyGHDL/dom/_Translate.py

* Fixed raising warnings.  
Raise `NotImplementedError` instances instead of raising simple `str` messages.
* Reactivated pyGHDL tests.

Fixed raising warnings in pyGHDL using pyTooling.
